openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / award_emoji'
  version: '1.0'
paths:
  '/projects/{id}/issues/{issue_iid}/award_emoji':
    get:
      summary: List an awardable’s award emojis
      description: Get a list of all award emojis for a specified awardable.
      operationId: listAnAwardableAwardEmojis
      parameters:
        - name: id
          in: path
          description: ID or URL-encoded path of the project.
          required: true
          schema:
            type: string
        - name: issue_iid/merge_request_iid/snippet_id
          in: query
          description: 'ID (iid for merge requests/issues, id for snippets) of an awardable.'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listAnAwardableAwardEmojisResponse'
      tags:
        - award_emoji
    post:
      summary: Award a new emoji
      description: Create an award emoji on the specified awardable.
      operationId: awardANewEmoji
      parameters:
        - name: id
          in: path
          description: ID or URL-encoded path of the project.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/awardANewEmojiResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/awardANewEmojiRequest'
      tags:
        - award_emoji
  '/projects/{id}/issues/{issue_iid}/award_emoji/{award_id}':
    get:
      summary: Get single award emoji
      description: 'Get a single award emoji from an issue, snippet, or merge request.'
      operationId: getSingleAwardEmoji
      parameters:
        - name: id
          in: path
          description: ID or URL-encoded path of the project.
          required: true
          schema:
            type: string
        - name: issue_iid/merge_request_iid/snippet_id
          in: query
          description: 'ID (iid for merge requests/issues, id for snippets) of an awardable.'
          required: true
          schema:
            type: integer
        - name: award_id
          in: path
          description: ID of the award emoji.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getSingleAwardEmojiResponse'
      tags:
        - award_emoji
    delete:
      summary: Delete an award emoji
      description: Sometimes it’s just not meant to be and you need to remove the award.
      operationId: deleteAnAwardEmoji
      parameters:
        - name: id
          in: path
          description: ID or URL-encoded path of the project.
          required: true
          schema:
            type: string
        - name: issue_iid/merge_request_iid/snippet_id
          in: query
          description: 'ID (iid for merge requests/issues, id for snippets) of an awardable.'
          required: true
          schema:
            type: integer
        - name: award_id
          in: path
          description: ID of an award emoji.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
      tags:
        - award_emoji
  '/projects/{id}/issues/{issue_iid}/notes/{note_id}/award_emoji':
    get:
      summary: List a comment’s award emojis
      description: Get all award emojis for a comment (note).
      operationId: listACommentAwardEmojis
      parameters:
        - name: id
          in: path
          description: ID or URL-encoded path of the project.
          required: true
          schema:
            type: string
        - name: issue_iid
          in: path
          description: Internal ID of an issue.
          required: true
          schema:
            type: integer
        - name: note_id
          in: path
          description: ID of a comment (note).
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listACommentAwardEmojisResponse'
      tags:
        - award_emoji
    post:
      summary: Award a new emoji on a comment
      description: Create an award emoji on the specified comment (note).
      operationId: awardANewEmojiOnAComment
      parameters:
        - name: id
          in: path
          description: ID or URL-encoded path of the project.
          required: true
          schema:
            type: string
        - name: issue_iid
          in: path
          description: Internal ID of an issue.
          required: true
          schema:
            type: integer
        - name: note_id
          in: path
          description: ID of a comment (note).
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/awardANewEmojiOnACommentResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/awardANewEmojiOnACommentRequest'
      tags:
        - award_emoji
  '/projects/{id}/issues/{issue_iid}/notes/{note_id}/award_emoji/{award_id}':
    get:
      summary: Get an award emoji for a comment
      description: Get a single award emoji for a comment (note).
      operationId: getAnAwardEmojiForAComment
      parameters:
        - name: id
          in: path
          description: ID or URL-encoded path of the project.
          required: true
          schema:
            type: string
        - name: issue_iid
          in: path
          description: Internal ID of an issue.
          required: true
          schema:
            type: integer
        - name: note_id
          in: path
          description: ID of a comment (note).
          required: true
          schema:
            type: integer
        - name: award_id
          in: path
          description: ID of the award emoji.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAnAwardEmojiForACommentResponse'
      tags:
        - award_emoji
    delete:
      summary: Delete an award emoji from a comment
      description: Sometimes it’s just not meant to be and you need to remove the award.
      operationId: deleteAnAwardEmojiFromAComment
      parameters:
        - name: id
          in: path
          description: ID or URL-encoded path of the project.
          required: true
          schema:
            type: string
        - name: issue_iid
          in: path
          description: Internal ID of an issue.
          required: true
          schema:
            type: integer
        - name: note_id
          in: path
          description: ID of a comment (note).
          required: true
          schema:
            type: integer
        - name: award_id
          in: path
          description: ID of an award_emoji.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
      tags:
        - award_emoji
components:
  schemas:
    listAnAwardableAwardEmojisResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          name:
            type: string
          user:
            type: object
            properties:
              name:
                type: string
              username:
                type: string
              id:
                type: integer
              state:
                type: string
              avatar_url:
                type: string
              web_url:
                type: string
          created_at:
            type: string
          updated_at:
            type: string
          awardable_id:
            type: integer
          awardable_type:
            type: string
    getSingleAwardEmojiResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        user:
          type: object
          properties:
            name:
              type: string
            username:
              type: string
            id:
              type: integer
            state:
              type: string
            avatar_url:
              type: string
            web_url:
              type: string
        created_at:
          type: string
        updated_at:
          type: string
        awardable_id:
          type: integer
        awardable_type:
          type: string
    awardANewEmojiRequest:
      type: object
      properties:
        issue_iid/merge_request_iid/snippet_id:
          type: integer
        name:
          type: string
      required:
        - issue_iid/merge_request_iid/snippet_id
        - name
    awardANewEmojiResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        user:
          type: object
          properties:
            name:
              type: string
            username:
              type: string
            id:
              type: integer
            state:
              type: string
            avatar_url:
              type: string
            web_url:
              type: string
        created_at:
          type: string
        updated_at:
          type: string
        awardable_id:
          type: integer
        awardable_type:
          type: string
    listACommentAwardEmojisResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          name:
            type: string
          user:
            type: object
            properties:
              name:
                type: string
              username:
                type: string
              id:
                type: integer
              state:
                type: string
              avatar_url:
                type: string
              web_url:
                type: string
          created_at:
            type: string
          updated_at:
            type: string
          awardable_id:
            type: integer
          awardable_type:
            type: string
    getAnAwardEmojiForACommentResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        user:
          type: object
          properties:
            name:
              type: string
            username:
              type: string
            id:
              type: integer
            state:
              type: string
            avatar_url:
              type: string
            web_url:
              type: string
        created_at:
          type: string
        updated_at:
          type: string
        awardable_id:
          type: integer
        awardable_type:
          type: string
    awardANewEmojiOnACommentRequest:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    awardANewEmojiOnACommentResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        user:
          type: object
          properties:
            name:
              type: string
            username:
              type: string
            id:
              type: integer
            state:
              type: string
            avatar_url:
              type: string
            web_url:
              type: string
        created_at:
          type: string
        updated_at:
          type: string
        awardable_id:
          type: integer
        awardable_type:
          type: string
