openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / deploy_tokens'
  version: '1.0'
paths:
  /deploy_tokens:
    get:
      summary: List all deploy tokens
      description: Get a list of all deploy tokens across the GitLab instance. This endpoint requires administrator access.
      operationId: listAllDeployTokens
      parameters:
        - name: active
          in: query
          description: Limit by active status.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listAllDeployTokensResponse'
      tags:
        - deploy_tokens
  '/projects/{id}/deploy_tokens':
    get:
      summary: List project deploy tokens
      description: Get a list of a project’s deploy tokens.
      operationId: listProjectDeployTokens
      parameters:
        - name: id
          in: path
          description: ID or URL-encoded path of the project.
          required: true
          schema:
            type: string
        - name: active
          in: query
          description: Limit by active status.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listAllDeployTokensResponse'
      tags:
        - deploy_tokens
    post:
      summary: Create a project deploy token
      description: Creates a new deploy token for a project.
      operationId: createAProjectDeployToken
      parameters:
        - name: id
          in: path
          description: ID or URL-encoded path of the project owned by the authenticated user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createAProjectDeployTokenResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createAProjectDeployTokenRequest'
      tags:
        - deploy_tokens
  '/projects/{id}/deploy_tokens/{token_id}':
    get:
      summary: Get a project deploy token
      description: Get a single project’s deploy token by ID.
      operationId: getAProjectDeployToken
      parameters:
        - name: id
          in: path
          description: ID or URL-encoded path of the project owned by the authenticated user
          required: true
          schema:
            type: string
        - name: token_id
          in: path
          description: ID of the deploy token
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAProjectDeployTokenResponse'
      tags:
        - deploy_tokens
    delete:
      summary: Delete a project deploy token
      description: Removes a deploy token from the project.
      operationId: deleteAProjectDeployToken
      parameters:
        - name: id
          in: path
          description: ID or URL-encoded path of the project owned by the authenticated user
          required: true
          schema:
            type: string
        - name: token_id
          in: path
          description: ID of the deploy token
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
      tags:
        - deploy_tokens
  '/groups/{id}/deploy_tokens':
    get:
      summary: List group deploy tokens
      description: Get a list of a group’s deploy tokens
      operationId: listGroupDeployTokens
      parameters:
        - name: id
          in: path
          description: ID or URL-encoded path of the project.
          required: true
          schema:
            type: string
        - name: active
          in: query
          description: Limit by active status.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listAllDeployTokensResponse'
      tags:
        - deploy_tokens
    post:
      summary: Create a group deploy token
      description: Creates a new deploy token for a group.
      operationId: createAGroupDeployToken
      parameters:
        - name: id
          in: path
          description: ID or URL-encoded path of the group owned by the authenticated user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createAProjectDeployTokenResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createAProjectDeployTokenRequest'
      tags:
        - deploy_tokens
  '/groups/{id}/deploy_tokens/{token_id}':
    get:
      summary: Get a group deploy token
      description: Get a single group’s deploy token by ID.
      operationId: getAGroupDeployToken
      parameters:
        - name: id
          in: path
          description: ID or URL-encoded path of the group owned by the authenticated user
          required: true
          schema:
            type: string
        - name: token_id
          in: path
          description: ID of the deploy token
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAProjectDeployTokenResponse'
      tags:
        - deploy_tokens
    delete:
      summary: Delete a group deploy token
      description: Removes a deploy token from the group.
      operationId: deleteAGroupDeployToken
      parameters:
        - name: id
          in: path
          description: ID or URL-encoded path of the group owned by the authenticated user
          required: true
          schema:
            type: string
        - name: token_id
          in: path
          description: ID of the deploy token
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
      tags:
        - deploy_tokens
components:
  schemas:
    listAllDeployTokensResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          name:
            type: string
          username:
            type: string
          expires_at:
            type: string
          revoked:
            type: boolean
          expired:
            type: boolean
          scopes:
            type: array
            items:
              type: string
    getAProjectDeployTokenResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        username:
          type: string
        expires_at:
          type: string
        revoked:
          type: boolean
        expired:
          type: boolean
        scopes:
          type: array
          items:
            type: string
    createAProjectDeployTokenRequest:
      type: object
      properties:
        name:
          type: string
        expires_at:
          type: string
          format: date-time
        username:
          type: string
        scopes:
          type: array
          items:
            type: string
    createAProjectDeployTokenResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        username:
          type: string
        expires_at:
          type: string
        token:
          type: string
        revoked:
          type: boolean
        expired:
          type: boolean
        scopes:
          type: array
          items:
            type: string
