openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / environments'
  version: '1.0'
paths:
  '/projects/{id}/environments':
    get:
      summary: List environments
      description: Get all environments for a given project.
      operationId: listEnvironments
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project owned by the authenticated user
          required: true
          schema:
            type: string
        - name: name
          in: query
          description: Return the environment with this name. Mutually exclusive with search
          required: false
          schema:
            type: string
        - name: search
          in: query
          description: Return list of environments matching the search criteria. Mutually exclusive with name
          required: false
          schema:
            type: string
        - name: states
          in: query
          description: >-
            List all environments that match a specific state. Accepted values: available or stopped. If no state value
            given, returns all environments.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listEnvironmentsResponse'
      tags:
        - environments
    post:
      summary: Create a new environment
      description: Creates a new environment with the given name and external_url.
      operationId: createANewEnvironment
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project owned by the authenticated user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createANewEnvironmentResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createANewEnvironmentRequest'
      tags:
        - environments
  '/projects/{id}/environments/{environment_id}':
    get:
      summary: Get a specific environment
      description: Example of response
      operationId: getASpecificEnvironment
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project owned by the authenticated user
          required: true
          schema:
            type: string
        - name: environment_id
          in: path
          description: The ID of the environment
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getASpecificEnvironmentResponse'
      tags:
        - environments
    put:
      summary: Edit an existing environment
      description: Updates an existing environment’s name and/or external_url.
      operationId: editAnExistingEnvironment
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project owned by the authenticated user
          required: true
          schema:
            type: string
        - name: environment_id
          in: path
          description: The ID of the environment
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createANewEnvironmentResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createANewEnvironmentRequest'
      tags:
        - environments
    delete:
      summary: Delete an environment
      description: 'It returns 204 if the environment was successfully deleted, and 404 if the environment does not exist.'
      operationId: deleteAnEnvironment
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project owned by the authenticated user
          required: true
          schema:
            type: string
        - name: environment_id
          in: path
          description: The ID of the environment
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
      tags:
        - environments
  '/projects/{id}/environments/review_apps':
    delete:
      summary: Delete multiple stopped review apps
      description: >-
        It schedules for deletion multiple environments that have already been stopped and are in the review app folder.
        The actual deletion is performed after 1 week from the time of execution.
      operationId: deleteMultipleStoppedReviewApps
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project owned by the authenticated user.
          required: true
          schema:
            type: string
        - name: before
          in: query
          description: >-
            The date before which environments can be deleted. Defaults to 30 days ago. Expected in ISO 8601 format
            (YYYY-MM-DDTHH:MM:SSZ).
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: Maximum number of environments to delete. Defaults to 100.
          required: false
          schema:
            type: integer
        - name: dry_run
          in: query
          description: >-
            Defaults to true for safety reasons. It performs a dry run where no actual deletion will be performed. Set
            to false to actually delete the environment.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deleteMultipleStoppedReviewAppsResponse'
      tags:
        - environments
  '/projects/{id}/environments/{environment_id}/stop':
    post:
      summary: Stop an environment
      description: 'It returns 200 if the environment was successfully stopped, and 404 if the environment does not exist.'
      operationId: stopAnEnvironment
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project owned by the authenticated user
          required: true
          schema:
            type: string
        - name: environment_id
          in: path
          description: The ID of the environment
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createANewEnvironmentResponse'
      tags:
        - environments
components:
  schemas:
    listEnvironmentsResponse:
      type: string
    getASpecificEnvironmentResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        slug:
          type: string
        external_url:
          type: string
        state:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        enable_advanced_logs_querying:
          type: boolean
        logs_api_path:
          type: string
        last_deployment:
          type: object
          properties:
            id:
              type: integer
            iid:
              type: integer
            ref:
              type: string
            sha:
              type: string
            created_at:
              type: string
              format: date-time
            status:
              type: string
            user:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                state:
                  type: string
                username:
                  type: string
                avatar_url:
                  type: string
                web_url:
                  type: string
            deployable:
              type: object
              properties:
                id:
                  type: integer
                status:
                  type: string
                stage:
                  type: string
                name:
                  type: string
                ref:
                  type: string
                tag:
                  type: boolean
                coverage:
                  type: string
                created_at:
                  type: string
                  format: date-time
                started_at:
                  type: string
                  format: date-time
                finished_at:
                  type: string
                  format: date-time
                duration:
                  type: number
                user:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    username:
                      type: string
                    state:
                      type: string
                    avatar_url:
                      type: string
                    web_url:
                      type: string
                    created_at:
                      type: string
                      format: date-time
                    bio:
                      type: string
                    location:
                      type: string
                    public_email:
                      type: string
                    skype:
                      type: string
                    linkedin:
                      type: string
                    twitter:
                      type: string
                    website_url:
                      type: string
                    organization:
                      type: string
                commit:
                  type: object
                  properties:
                    id:
                      type: string
                    short_id:
                      type: string
                    created_at:
                      type: string
                      format: date-time
                    parent_ids:
                      type: array
                      items:
                        type: string
                    title:
                      type: string
                    message:
                      type: string
                    author_name:
                      type: string
                    author_email:
                      type: string
                    authored_date:
                      type: string
                    committer_name:
                      type: string
                    committer_email:
                      type: string
                    committed_date:
                      type: string
                pipeline:
                  type: object
                  properties:
                    id:
                      type: integer
                    sha:
                      type: string
                    ref:
                      type: string
                    status:
                      type: string
                    web_url:
                      type: string
                web_url:
                  type: string
                artifacts:
                  type: array
                  items:
                    type: object
                    properties:
                      file_type:
                        type: string
                      size:
                        type: integer
                      filename:
                        type: string
                      file_format:
                        type: string
                runner:
                  type: string
                artifacts_expire_at:
                  type: string
    createANewEnvironmentRequest:
      type: object
      properties:
        name:
          type: string
        external_url:
          type: string
      required:
        - name
    createANewEnvironmentResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        slug:
          type: string
        external_url:
          type: string
        state:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    deleteMultipleStoppedReviewAppsResponse:
      type: object
      properties:
        scheduled_entries:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              slug:
                type: string
              external_url:
                type: string
        unprocessable_entries:
          type: array
          items: {}
