openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / features'
  version: '1.0'
paths:
  /features:
    get:
      summary: List all features
      description: 'Get a list of all persisted features, with its gate values.'
      operationId: listAllFeatures
      parameters: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listAllFeaturesResponse'
  /features/definitions:
    get:
      summary: List all feature definitions
      description: Get a list of all feature definitions.
      operationId: listAllFeatureDefinitions
      parameters: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listAllFeatureDefinitionsResponse'
  '/features/{name}':
    post:
      summary: Set or create a feature
      description: >-
        Set a feature’s gate value. If a feature with the given name doesn’t exist yet, it’s created. The value can be a
        boolean, or an integer to indicate percentage of time.
      operationId: setOrCreateAFeature
      parameters:
        - name: name
          in: path
          description: Name of the feature to create or update
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/setOrCreateAFeatureResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/setOrCreateAFeatureRequest'
    delete:
      summary: Delete a feature
      description: 'Removes a feature gate. Response is equal when the gate exists, or doesn’t.'
      operationId: deleteAFeature
      parameters: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deleteAFeatureResponse'
  'https://gitlab.example.com/api/v4/features/my_user_feature':
    post:
      summary: Set percentage of actors rollout
      description: Rollout to percentage of actors.
      operationId: setPercentageOfActorsRollout
      parameters: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/setPercentageOfActorsRolloutResponse'
components:
  schemas:
    listAllFeaturesResponse:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
          state:
            type: string
          gates:
            type: array
            items:
              type: object
              properties:
                key:
                  type: string
                value:
                  type: boolean
          definition:
            type: string
    listAllFeatureDefinitionsResponse:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
          introduced_by_url:
            type: string
          rollout_issue_url:
            type: string
          milestone:
            type: string
          log_state_changes:
            type: string
          type:
            type: string
          group:
            type: string
          default_enabled:
            type: boolean
    setOrCreateAFeatureRequest:
      type: object
      properties:
        value:
          oneOf:
            - type: integer
            - type: string
        key:
          type: string
        feature_group:
          type: string
        user:
          type: string
        group:
          type: string
        project:
          type: string
        force:
          type: boolean
      required:
        - value
    setOrCreateAFeatureResponse:
      type: object
      properties:
        name:
          type: string
        state:
          type: string
        gates:
          type: array
          items:
            type: object
            properties:
              key:
                type: string
              value:
                type: boolean
        definition:
          type: object
          properties:
            name:
              type: string
            introduced_by_url:
              type: string
            rollout_issue_url:
              type: string
            group:
              type: string
            type:
              type: string
            default_enabled:
              type: boolean
    setPercentageOfActorsRolloutResponse:
      type: object
      properties:
        name:
          type: string
        state:
          type: string
        gates:
          type: array
          items:
            type: object
            properties:
              key:
                type: string
              value:
                type: boolean
        definition:
          type: object
          properties:
            name:
              type: string
            introduced_by_url:
              type: string
            rollout_issue_url:
              type: string
            group:
              type: string
            type:
              type: string
            default_enabled:
              type: boolean
    deleteAFeatureResponse:
      type: string
