openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / group_labels'
  version: '1.0'
paths:
  '/groups/{id}/labels':
    get:
      summary: List group labels
      description: Get all labels for a given group.
      operationId: listGroupLabels
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user.
          required: true
          schema:
            type: string
        - name: with_counts
          in: query
          description: Whether or not to include issue and merge request counts. Defaults to false. (Introduced in GitLab 12.2)
          required: false
          schema:
            type: string
        - name: include_ancestor_groups
          in: query
          description: Include ancestor groups. Defaults to true.
          required: false
          schema:
            type: string
        - name: include_descendant_groups
          in: query
          description: Include descendant groups. Defaults to false. Introduced in GitLab 13.6
          required: false
          schema:
            type: string
        - name: only_group_labels
          in: query
          description: Toggle to include only group labels or also project labels. Defaults to true. Introduced in GitLab 13.6
          required: false
          schema:
            type: string
        - name: search
          in: query
          description: Keyword to filter labels by. Introduced in GitLab 13.6
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listGroupLabelsResponse'
    post:
      summary: Create a new group label
      description: Create a new group label for a given group.
      operationId: createANewGroupLabel
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createANewGroupLabelResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createANewGroupLabelRequest'
  '/groups/{id}/labels/{label_id}':
    get:
      summary: Get a single group label
      description: Get a single label for a given group.
      operationId: getASingleGroupLabel
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user.
          required: true
          schema:
            type: string
        - name: label_id
          in: path
          description: The ID or title of a group’s label.
          required: true
          schema:
            type: string
        - name: include_ancestor_groups
          in: query
          description: Include ancestor groups. Defaults to true.
          required: false
          schema:
            type: string
        - name: include_descendant_groups
          in: query
          description: Include descendant groups. Defaults to false. Introduced in GitLab 13.6
          required: false
          schema:
            type: string
        - name: only_group_labels
          in: query
          description: Toggle to include only group labels or also project labels. Defaults to true. Introduced in GitLab 13.6
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getASingleGroupLabelResponse'
    put:
      summary: Update a group label
      description: 'Updates an existing group label. At least one parameter is required, to update the group label.'
      operationId: updateAGroupLabel
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user
          required: true
          schema:
            type: string
        - name: label_id
          in: path
          description: The ID or title of a group’s label.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updateAGroupLabelResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateAGroupLabelRequest'
    delete:
      summary: Delete a group label
      description: Deletes a group label with a given name.
      operationId: deleteAGroupLabel
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user
          required: true
          schema:
            type: string
        - name: label_id
          in: path
          description: The ID or title of a group’s label.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deleteAGroupLabelResponse'
  '/groups/{id}/labels/{label_id}/subscribe':
    post:
      summary: Subscribe to a group label
      description: >-
        Subscribes the authenticated user to a group label to receive notifications. If the user is already subscribed
        to the label, the status code 304 is returned.
      operationId: subscribeToAGroupLabel
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user
          required: true
          schema:
            type: string
        - name: label_id
          in: path
          description: The ID or title of a group’s label.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subscribeToAGroupLabelResponse'
  '/groups/{id}/labels/{label_id}/unsubscribe':
    post:
      summary: Unsubscribe from a group label
      description: >-
        Unsubscribes the authenticated user from a group label to not receive notifications from it. If the user is not
        subscribed to the label, the status code 304 is returned.
      operationId: unsubscribeFromAGroupLabel
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user
          required: true
          schema:
            type: string
        - name: label_id
          in: path
          description: The ID or title of a group’s label.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unsubscribeFromAGroupLabelResponse'
components:
  schemas:
    listGroupLabelsResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          name:
            type: string
          color:
            type: string
          text_color:
            type: string
          description:
            type: string
          description_html:
            type: string
          open_issues_count:
            type: integer
          closed_issues_count:
            type: integer
          open_merge_requests_count:
            type: integer
          subscribed:
            type: boolean
    getASingleGroupLabelResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        color:
          type: string
        text_color:
          type: string
        description:
          type: string
        description_html:
          type: string
        open_issues_count:
          type: integer
        closed_issues_count:
          type: integer
        open_merge_requests_count:
          type: integer
        subscribed:
          type: boolean
    createANewGroupLabelRequest:
      type: object
      properties:
        name:
          type: string
        color:
          type: string
        description:
          type: string
      required:
        - name
        - color
    createANewGroupLabelResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        color:
          type: string
        text_color:
          type: string
        description:
          type: string
        description_html:
          type: string
        open_issues_count:
          type: integer
        closed_issues_count:
          type: integer
        open_merge_requests_count:
          type: integer
        subscribed:
          type: boolean
    updateAGroupLabelRequest:
      type: object
      properties:
        new_name:
          type: string
        color:
          type: string
        description:
          type: string
    updateAGroupLabelResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        color:
          type: string
        text_color:
          type: string
        description:
          type: string
        description_html:
          type: string
        open_issues_count:
          type: integer
        closed_issues_count:
          type: integer
        open_merge_requests_count:
          type: integer
        subscribed:
          type: boolean
    deleteAGroupLabelResponse:
      type: string
    subscribeToAGroupLabelResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        color:
          type: string
        text_color:
          type: string
        description:
          type: string
        description_html:
          type: string
        open_issues_count:
          type: integer
        closed_issues_count:
          type: integer
        open_merge_requests_count:
          type: integer
        subscribed:
          type: boolean
    unsubscribeFromAGroupLabelResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        color:
          type: string
        text_color:
          type: string
        description:
          type: string
        description_html:
          type: string
        open_issues_count:
          type: integer
        closed_issues_count:
          type: integer
        open_merge_requests_count:
          type: integer
        subscribed:
          type: boolean
