openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / group_milestones'
  version: '1.0'
paths:
  '/groups/{id}/milestones':
    get:
      summary: List group milestones
      description: Returns a list of group milestones.
      operationId: listGroupMilestones
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user
          required: true
          schema:
            type: string
        - name: 'iids[]'
          in: query
          description: 'Return only the milestones having the given iid (Note: ignored if include_parent_milestones is set as true)'
          required: false
          schema:
            type: string
        - name: state
          in: query
          description: Return only active or closed milestones
          required: false
          schema:
            type: string
        - name: title
          in: query
          description: Return only the milestones having the given title
          required: false
          schema:
            type: string
        - name: search
          in: query
          description: Return only milestones with a title or description matching the provided string
          required: false
          schema:
            type: string
        - name: include_parent_milestones
          in: query
          description: Include milestones from parent group and its ancestors. Introduced in GitLab 13.4
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listGroupMilestonesResponse'
      tags:
        - group_milestones
    post:
      summary: Create new milestone
      description: Creates a new group milestone.
      operationId: createNewMilestone
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createNewMilestoneResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createNewMilestoneRequest'
      tags:
        - group_milestones
  '/groups/{id}/milestones/{milestone_id}':
    get:
      summary: Get single milestone
      description: Gets a single group milestone.
      operationId: getSingleMilestone
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user
          required: true
          schema:
            type: string
        - name: milestone_id
          in: path
          description: The ID of the group milestone
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getSingleMilestoneResponse'
      tags:
        - group_milestones
    put:
      summary: Edit milestone
      description: Updates an existing group milestone.
      operationId: editMilestone
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user
          required: true
          schema:
            type: string
        - name: milestone_id
          in: path
          description: The ID of a group milestone
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/editMilestoneResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/editMilestoneRequest'
      tags:
        - group_milestones
    delete:
      summary: Delete group milestone
      description: Only for users with the Developer role in the group.
      operationId: deleteGroupMilestone
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user
          required: true
          schema:
            type: string
        - name: milestone_id
          in: path
          description: The ID of the group’s milestone
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deleteGroupMilestoneResponse'
      tags:
        - group_milestones
  '/groups/{id}/milestones/{milestone_id}/issues':
    get:
      summary: Get all issues assigned to a single milestone
      description: Gets all issues assigned to a single group milestone.
      operationId: getAllIssuesAssignedToASingleMilestone
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user
          required: true
          schema:
            type: string
        - name: milestone_id
          in: path
          description: The ID of a group milestone
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAllIssuesAssignedToASingleMilestoneResponse'
      tags:
        - group_milestones
  '/groups/{id}/milestones/{milestone_id}/merge_requests':
    get:
      summary: Get all merge requests assigned to a single milestone
      description: Gets all merge requests assigned to a single group milestone.
      operationId: getAllMergeRequestsAssignedToASingleMilestone
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user
          required: true
          schema:
            type: string
        - name: milestone_id
          in: path
          description: The ID of a group milestone
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAllMergeRequestsAssignedToASingleMilestoneResponse'
      tags:
        - group_milestones
  '/groups/{id}/milestones/{milestone_id}/burndown_events':
    get:
      summary: Get all burndown chart events for a single milestone
      description: Get all burndown chart events for a single milestone.
      operationId: getAllBurndownChartEventsForASingleMilestone
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user
          required: true
          schema:
            type: string
        - name: milestone_id
          in: path
          description: The ID of a group milestone
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAllBurndownChartEventsForASingleMilestoneResponse'
      tags:
        - group_milestones
components:
  schemas:
    listGroupMilestonesResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          iid:
            type: integer
          group_id:
            type: integer
          title:
            type: string
          description:
            type: string
          due_date:
            type: string
          start_date:
            type: string
          state:
            type: string
          updated_at:
            type: string
          created_at:
            type: string
          expired:
            type: boolean
          web_url:
            type: string
    getSingleMilestoneResponse:
      type: string
    createNewMilestoneRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        due_date:
          type: string
          format: date
        start_date:
          type: string
          format: date
      required:
        - title
    createNewMilestoneResponse:
      type: string
    editMilestoneRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        due_date:
          type: string
          format: date
        start_date:
          type: string
          format: date
        state_event:
          type: string
    editMilestoneResponse:
      type: string
    deleteGroupMilestoneResponse:
      type: string
    getAllIssuesAssignedToASingleMilestoneResponse:
      type: string
    getAllMergeRequestsAssignedToASingleMilestoneResponse:
      type: string
    getAllBurndownChartEventsForASingleMilestoneResponse:
      type: string
