openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / group_badges'
  version: '1.0'
paths:
  '/groups/{id}/badges':
    get:
      summary: List all badges of a group
      description: Gets a list of a group’s badges.
      operationId: listAllBadgesOfAGroup
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user
          required: true
          schema:
            type: string
        - name: name
          in: query
          description: Name of the badges to return (case-sensitive).
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listAllBadgesOfAGroupResponse'
      tags:
        - group_badges
    post:
      summary: Add a badge to a group
      description: Adds a badge to a group.
      operationId: addABadgeToAGroup
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addABadgeToAGroupResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addABadgeToAGroupRequest'
      tags:
        - group_badges
  '/groups/{id}/badges/{badge_id}':
    get:
      summary: Get a badge of a group
      description: Gets a badge of a group.
      operationId: getABadgeOfAGroup
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user
          required: true
          schema:
            type: string
        - name: badge_id
          in: path
          description: The badge ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getABadgeOfAGroupResponse'
      tags:
        - group_badges
    put:
      summary: Edit a badge of a group
      description: Updates a badge of a group.
      operationId: editABadgeOfAGroup
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user
          required: true
          schema:
            type: string
        - name: badge_id
          in: path
          description: The badge ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/editABadgeOfAGroupResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/editABadgeOfAGroupRequest'
      tags:
        - group_badges
    delete:
      summary: Remove a badge from a group
      description: Removes a badge from a group.
      operationId: removeABadgeFromAGroup
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user
          required: true
          schema:
            type: string
        - name: badge_id
          in: path
          description: The badge ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/removeABadgeFromAGroupResponse'
      tags:
        - group_badges
  '/groups/{id}/badges/render':
    get:
      summary: Preview a badge from a group
      description: Returns how the link_url and image_url final URLs would be after resolving the placeholder interpolation.
      operationId: previewABadgeFromAGroup
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user
          required: true
          schema:
            type: string
        - name: link_url
          in: query
          description: URL of the badge link
          required: true
          schema:
            type: string
        - name: image_url
          in: query
          description: URL of the badge image
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/previewABadgeFromAGroupResponse'
      tags:
        - group_badges
components:
  schemas:
    listAllBadgesOfAGroupResponse:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
          id:
            type: integer
          link_url:
            type: string
          image_url:
            type: string
          rendered_link_url:
            type: string
          rendered_image_url:
            type: string
          kind:
            type: string
    getABadgeOfAGroupResponse:
      type: object
      properties:
        id:
          type: integer
        link_url:
          type: string
        image_url:
          type: string
        rendered_link_url:
          type: string
        rendered_image_url:
          type: string
        kind:
          type: string
    addABadgeToAGroupRequest:
      type: object
      properties:
        link_url:
          type: string
        image_url:
          type: string
      required:
        - link_url
        - image_url
    addABadgeToAGroupResponse:
      type: object
      properties:
        id:
          type: integer
        link_url:
          type: string
        image_url:
          type: string
        rendered_link_url:
          type: string
        rendered_image_url:
          type: string
        kind:
          type: string
    editABadgeOfAGroupRequest:
      type: object
      properties:
        link_url:
          type: string
        image_url:
          type: string
    editABadgeOfAGroupResponse:
      type: object
      properties:
        id:
          type: integer
        link_url:
          type: string
        image_url:
          type: string
        rendered_link_url:
          type: string
        rendered_image_url:
          type: string
        kind:
          type: string
    removeABadgeFromAGroupResponse:
      type: string
    previewABadgeFromAGroupResponse:
      type: object
      properties:
        link_url:
          type: string
        image_url:
          type: string
        rendered_link_url:
          type: string
        rendered_image_url:
          type: string
