openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / import'
  version: '1.0'
paths:
  /import/github:
    post:
      summary: Import repository from GitHub
      description: Import your projects from GitHub to GitLab via the API.
      operationId: importRepositoryFromGithub
      parameters: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/importRepositoryFromGithubResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/importRepositoryFromGithubRequest'
      tags:
        - import
  /import/bitbucket_server:
    post:
      summary: Import repository from Bitbucket Server
      description: Import your projects from Bitbucket Server to GitLab via the API.
      operationId: importRepositoryFromBitbucketServer
      parameters: []
      responses:
        '200':
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/importRepositoryFromBitbucketServerRequest'
      tags:
        - import
components:
  schemas:
    importRepositoryFromGithubRequest:
      type: object
      properties:
        personal_access_token:
          type: string
        repo_id:
          type: integer
        new_name:
          type: string
        target_namespace:
          type: string
        github_hostname:
          type: string
      required:
        - personal_access_token
        - repo_id
        - target_namespace
    importRepositoryFromGithubResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        full_path:
          type: string
        full_name:
          type: string
    importRepositoryFromBitbucketServerRequest:
      type: object
      properties:
        bitbucket_server_url:
          type: string
        bitbucket_server_username:
          type: string
        personal_access_token:
          type: string
        bitbucket_server_project:
          type: string
        bitbucket_server_repo:
          type: string
        new_name:
          type: string
        target_namespace:
          type: string
      required:
        - bitbucket_server_url
        - bitbucket_server_username
        - personal_access_token
        - bitbucket_server_project
        - bitbucket_server_repo
