openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / invitations'
  version: '1.0'
paths:
  '/groups/{id}/invitations':
    post:
      summary: Add a member to a group or project
      description: Adds a new member. You can specify a user ID or invite a user by email.
      operationId: addAMemberToAGroupOrProject
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project or group owned by the authenticated user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addAMemberToAGroupOrProjectResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addAMemberToAGroupOrProjectRequest'
      tags:
        - invitations
    get:
      summary: List all invitations pending for a group or project
      description: >-
        Gets a list of invited group or project members viewable by the authenticated user. Returns invitations to
        direct members only, and not through inherited ancestors’ groups.
      operationId: listAllInvitationsPendingForAGroupOrProject
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project or group owned by the authenticated user
          required: true
          schema:
            type: string
        - name: page
          in: query
          description: Page to retrieve
          required: false
          schema:
            type: integer
        - name: per_page
          in: query
          description: Number of member invitations to return per page
          required: false
          schema:
            type: integer
        - name: query
          in: query
          description: >-
            A query string to search for invited members by invite email. Query text must match email address exactly.
            When empty, returns all invitations.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listAllInvitationsPendingForAGroupOrProjectResponse'
      tags:
        - invitations
  '/groups/{id}/invitations/{email}':
    put:
      summary: Update an invitation to a group or project
      description: Updates a pending invitation’s access level or access expiry date.
      operationId: updateAnInvitationToAGroupOrProject
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project or group owned by the authenticated user.
          required: true
          schema:
            type: string
        - name: email
          in: path
          description: The email address to which the invitation was previously sent.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updateAnInvitationToAGroupOrProjectResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateAnInvitationToAGroupOrProjectRequest'
      tags:
        - invitations
    delete:
      summary: Delete an invitation to a group or project
      description: Deletes a pending invitation by email address.
      operationId: deleteAnInvitationToAGroupOrProject
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project or group owned by the authenticated user
          required: true
          schema:
            type: string
        - name: email
          in: path
          description: The email address to which the invitation was previously sent
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
      tags:
        - invitations
components:
  schemas:
    addAMemberToAGroupOrProjectRequest:
      type: object
      properties:
        email:
          type: string
        user_id:
          oneOf:
            - type: integer
            - type: string
        access_level:
          type: integer
        expires_at:
          type: string
        invite_source:
          type: string
        tasks_to_be_done:
          type: array
          items:
            type: string
        tasks_project_id:
          type: integer
      required:
        - access_level
    addAMemberToAGroupOrProjectResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: object
          properties:
            test@example.com:
              type: string
            test2@example.com:
              type: string
            test_username:
              type: string
    listAllInvitationsPendingForAGroupOrProjectResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          invite_email:
            type: string
          created_at:
            type: string
          access_level:
            type: integer
          expires_at:
            type: string
          user_name:
            type: string
          created_by_name:
            type: string
    updateAnInvitationToAGroupOrProjectRequest:
      type: object
      properties:
        access_level:
          type: integer
        expires_at:
          type: string
    updateAnInvitationToAGroupOrProjectResponse:
      type: object
      properties:
        expires_at:
          type: string
        access_level:
          type: integer
