openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / packages'
  version: '1.0'
paths:
  '/projects/{id}/packages':
    get:
      summary: Within a project
      description: >-
        Get a list of project packages. All package types are included in results. When accessed without authentication,
        only packages of public projects are returned.
      operationId: withinAProject
      parameters:
        - name: id
          in: path
          description: ID or URL-encoded path of the project
          required: true
          schema:
            type: string
        - name: order_by
          in: query
          description: 'The field to use as order. One of created_at (default), name, version, or type.'
          required: false
          schema:
            type: string
        - name: sort
          in: query
          description: 'The direction of the order, either asc (default) for ascending order or desc for descending order.'
          required: false
          schema:
            type: string
        - name: package_type
          in: query
          description: >-
            Filter the returned packages by type. One of conan, maven, npm, pypi, composer, nuget, helm,
            terraform_module, or golang. (Introduced in GitLab 12.9)
          required: false
          schema:
            type: string
        - name: package_name
          in: query
          description: Filter the project packages with a fuzzy search by name. (Introduced in GitLab 12.9)
          required: false
          schema:
            type: string
        - name: include_versionless
          in: query
          description: 'When set to true, versionless packages are included in the response. (Introduced in GitLab 13.8)'
          required: false
          schema:
            type: string
        - name: status
          in: query
          description: >-
            Filter the returned packages by status. One of default (default), hidden, or processing. (Introduced in
            GitLab 13.9)
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/withinAProjectResponse'
      tags:
        - packages
  '/groups/{id}/packages':
    get:
      summary: Within a group
      description: >-
        Get a list of project packages at the group level. When accessed without authentication, only packages of public
        projects are returned.
      operationId: withinAGroup
      parameters:
        - name: id
          in: path
          description: ID or URL-encoded path of the group.
          required: true
          schema:
            type: string
        - name: exclude_subgroups
          in: query
          description: >-
            If the parameter is included as true, packages from projects from subgroups are not listed. Default is
            false.
          required: false
          schema:
            type: string
        - name: order_by
          in: query
          description: 'The field to use as order. One of created_at (default), name, version, type, or project_path.'
          required: false
          schema:
            type: string
        - name: sort
          in: query
          description: 'The direction of the order, either asc (default) for ascending order or desc for descending order.'
          required: false
          schema:
            type: string
        - name: package_type
          in: query
          description: >-
            Filter the returned packages by type. One of conan, maven, npm, pypi, composer, nuget, helm, or golang.
            (Introduced in GitLab 12.9)
          required: false
          schema:
            type: string
        - name: package_name
          in: query
          description: Filter the project packages with a fuzzy search by name. (Introduced in GitLab 13.0)
          required: false
          schema:
            type: string
        - name: include_versionless
          in: query
          description: 'When set to true, versionless packages are included in the response. (Introduced in GitLab 13.8)'
          required: false
          schema:
            type: string
        - name: status
          in: query
          description: >-
            Filter the returned packages by status. One of default (default), hidden, or processing. (Introduced in
            GitLab 13.9)
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/withinAGroupResponse'
      tags:
        - packages
  '/projects/{id}/packages/{package_id}':
    get:
      summary: Get a project package
      description: Get a single project package.
      operationId: getAProjectPackage
      parameters:
        - name: id
          in: path
          description: ID or URL-encoded path of the project.
          required: true
          schema:
            type: string
        - name: package_id
          in: path
          description: ID of a package.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAProjectPackageResponse'
      tags:
        - packages
    delete:
      summary: Delete a project package
      description: Deletes a project package.
      operationId: deleteAProjectPackage
      parameters:
        - name: id
          in: path
          description: ID or URL-encoded path of the project
          required: true
          schema:
            type: string
        - name: package_id
          in: path
          description: ID of a package.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
      tags:
        - packages
  '/projects/{id}/packages/{package_id}/package_files':
    get:
      summary: List package files
      description: Get a list of package files of a single package.
      operationId: listPackageFiles
      parameters:
        - name: id
          in: path
          description: ID or URL-encoded path of the project
          required: true
          schema:
            type: string
        - name: package_id
          in: path
          description: ID of a package.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listPackageFilesResponse'
      tags:
        - packages
  '/projects/{id}/packages/{package_id}/package_files/{package_file_id}':
    delete:
      summary: Delete a package file
      description: 'Delete a package file:'
      operationId: deleteAPackageFile
      parameters:
        - name: id
          in: path
          description: ID or URL-encoded path of the project.
          required: true
          schema:
            type: string
        - name: package_id
          in: path
          description: ID of a package.
          required: true
          schema:
            type: integer
        - name: package_file_id
          in: path
          description: ID of a package file.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
      tags:
        - packages
components:
  schemas:
    withinAProjectResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          name:
            type: string
          version:
            type: string
          package_type:
            type: string
          created_at:
            type: string
            format: date-time
    withinAGroupResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          name:
            type: string
          version:
            type: string
          package_type:
            type: string
          _links:
            type: object
            properties:
              web_path:
                type: string
              delete_api_path:
                type: string
          created_at:
            type: string
            format: date-time
          pipelines:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                status:
                  type: string
                ref:
                  type: string
                sha:
                  type: string
                web_url:
                  type: string
                created_at:
                  type: string
                  format: date-time
                updated_at:
                  type: string
                  format: date-time
                user:
                  type: object
                  properties:
                    name:
                      type: string
                    avatar_url:
                      type: string
    getAProjectPackageResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        version:
          type: string
        package_type:
          type: string
        _links:
          type: object
          properties:
            web_path:
              type: string
            delete_api_path:
              type: string
        created_at:
          type: string
          format: date-time
        pipelines:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              status:
                type: string
              ref:
                type: string
              sha:
                type: string
              web_url:
                type: string
              created_at:
                type: string
                format: date-time
              updated_at:
                type: string
                format: date-time
              user:
                type: object
                properties:
                  name:
                    type: string
                  avatar_url:
                    type: string
        versions:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              version:
                type: string
              created_at:
                type: string
                format: date-time
              pipelines:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    status:
                      type: string
                    ref:
                      type: string
                    sha:
                      type: string
                    web_url:
                      type: string
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                    user:
                      type: object
                      properties:
                        name:
                          type: string
                        avatar_url:
                          type: string
    listPackageFilesResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          package_id:
            type: integer
          created_at:
            type: string
            format: date-time
          file_name:
            type: string
          size:
            type: integer
          file_md5:
            type: string
          file_sha1:
            type: string
          file_sha256:
            type: string
          pipelines:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                status:
                  type: string
                ref:
                  type: string
                sha:
                  type: string
                web_url:
                  type: string
                created_at:
                  type: string
                  format: date-time
                updated_at:
                  type: string
                  format: date-time
                user:
                  type: object
                  properties:
                    name:
                      type: string
                    avatar_url:
                      type: string
