openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / pages_domains'
  version: '1.0'
paths:
  /pages/domains:
    get:
      summary: List all Pages domains
      description: Get a list of all Pages domains. The user must have administrator access.
      operationId: listAllPagesDomains
      parameters: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listAllPagesDomainsResponse'
      tags:
        - pages_domains
  '/projects/{id}/pages/domains':
    get:
      summary: List Pages domains
      description: Get a list of project Pages domains. The user must have permissions to view Pages domains.
      operationId: listPagesDomains
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project owned by the authenticated user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listPagesDomainsResponse'
      tags:
        - pages_domains
    post:
      summary: Create new Pages domain
      description: Creates a new Pages domain. The user must have permissions to create new Pages domains.
      operationId: createNewPagesDomain
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project owned by the authenticated user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/singlePagesDomainResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createNewPagesDomainRequest'
      tags:
        - pages_domains
  '/projects/{id}/pages/domains/{domain}':
    get:
      summary: Single Pages domain
      description: Get a single project Pages domain. The user must have permissions to view Pages domains.
      operationId: singlePagesDomain
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project owned by the authenticated user
          required: true
          schema:
            type: string
        - name: domain
          in: path
          description: The custom domain indicated by the user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/singlePagesDomainResponse'
      tags:
        - pages_domains
    put:
      summary: Update Pages domain
      description: Updates an existing project Pages domain. The user must have permissions to change an existing Pages domains.
      operationId: updatePagesDomain
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project owned by the authenticated user
          required: true
          schema:
            type: string
        - name: domain
          in: path
          description: The custom domain indicated by the user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updatePagesDomainRequest'
      tags:
        - pages_domains
    delete:
      summary: Delete Pages domain
      description: Deletes an existing project Pages domain.
      operationId: deletePagesDomain
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project owned by the authenticated user
          required: true
          schema:
            type: string
        - name: domain
          in: path
          description: The custom domain indicated by the user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
      tags:
        - pages_domains
components:
  schemas:
    listAllPagesDomainsResponse:
      type: array
      items:
        type: object
        properties:
          domain:
            type: string
          url:
            type: string
          project_id:
            type: integer
          auto_ssl_enabled:
            type: boolean
          certificate:
            type: object
            properties:
              expired:
                type: boolean
              expiration:
                type: string
    listPagesDomainsResponse:
      type: array
      items:
        type: object
        properties:
          domain:
            type: string
          url:
            type: string
    singlePagesDomainResponse:
      type: object
      properties:
        domain:
          type: string
        url:
          type: string
        auto_ssl_enabled:
          type: boolean
        certificate:
          type: object
          properties:
            subject:
              type: string
            expired:
              type: boolean
            certificate:
              type: string
            certificate_text:
              type: string
    createNewPagesDomainRequest:
      type: object
      properties:
        domain:
          type: string
        auto_ssl_enabled:
          type: boolean
      required:
        - domain
    updatePagesDomainRequest:
      type: object
      properties:
        auto_ssl_enabled:
          type: boolean
