openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / releases__links'
  version: '1.0'
paths:
  '/projects/{id}/releases/{tag_name}/assets/links':
    get:
      summary: Get links
      description: Get assets as links from a Release.
      operationId: getLinks
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project.
          required: true
          schema:
            type: string
        - name: tag_name
          in: path
          description: The tag associated with the Release.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getLinksResponse'
    post:
      summary: Create a link
      description: Create an asset as a link from a Release.
      operationId: createALink
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project.
          required: true
          schema:
            type: string
        - name: tag_name
          in: path
          description: The tag associated with the Release.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createALinkResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createALinkRequest'
  '/projects/{id}/releases/{tag_name}/assets/links/{link_id}':
    get:
      summary: Get a link
      description: Get an asset as a link from a Release.
      operationId: getALink
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project.
          required: true
          schema:
            type: string
        - name: tag_name
          in: path
          description: The tag associated with the Release.
          required: true
          schema:
            type: string
        - name: link_id
          in: path
          description: The ID of the link.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getALinkResponse'
    put:
      summary: Update a link
      description: Update an asset as a link from a Release.
      operationId: updateALink
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project.
          required: true
          schema:
            type: string
        - name: tag_name
          in: path
          description: The tag associated with the Release.
          required: true
          schema:
            type: string
        - name: link_id
          in: path
          description: The ID of the link.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updateALinkResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateALinkRequest'
    delete:
      summary: Delete a link
      description: Delete an asset as a link from a Release.
      operationId: deleteALink
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project.
          required: true
          schema:
            type: string
        - name: tag_name
          in: path
          description: The tag associated with the Release.
          required: true
          schema:
            type: string
        - name: link_id
          in: path
          description: The ID of the link.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deleteALinkResponse'
components:
  schemas:
    getLinksResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          name:
            type: string
          url:
            type: string
          external:
            type: boolean
          link_type:
            type: string
    getALinkResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        url:
          type: string
        external:
          type: boolean
        link_type:
          type: string
    createALinkRequest:
      type: object
      properties:
        name:
          type: string
        url:
          type: string
        filepath:
          type: string
        link_type:
          type: string
      required:
        - name
        - url
    createALinkResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        url:
          type: string
        direct_asset_url:
          type: string
        external:
          type: boolean
        link_type:
          type: string
    updateALinkRequest:
      type: object
      properties:
        name:
          type: string
        url:
          type: string
        filepath:
          type: string
        link_type:
          type: string
    updateALinkResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        url:
          type: string
        external:
          type: boolean
        link_type:
          type: string
    deleteALinkResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        url:
          type: string
        external:
          type: boolean
        link_type:
          type: string
