openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / resource_label_events'
  version: '1.0'
paths:
  '/projects/{id}/issues/{issue_iid}/resource_label_events':
    get:
      summary: List project issue label events
      description: Gets a list of all label events for a single issue.
      operationId: listProjectIssueLabelEvents
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project
          required: true
          schema:
            type: string
        - name: issue_iid
          in: path
          description: The IID of an issue
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listProjectIssueLabelEventsResponse'
      tags:
        - resource_label_events
  '/projects/{id}/issues/{issue_iid}/resource_label_events/{resource_label_event_id}':
    get:
      summary: Get single issue label event
      description: Returns a single label event for a specific project issue
      operationId: getSingleIssueLabelEvent
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project
          required: true
          schema:
            type: string
        - name: issue_iid
          in: path
          description: The IID of an issue
          required: true
          schema:
            type: integer
        - name: resource_label_event_id
          in: path
          description: The ID of a label event
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
      tags:
        - resource_label_events
  '/groups/{id}/epics/{epic_id}/resource_label_events':
    get:
      summary: List group epic label events
      description: Gets a list of all label events for a single epic.
      operationId: listGroupEpicLabelEvents
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group
          required: true
          schema:
            type: string
        - name: epic_id
          in: path
          description: The ID of an epic
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listProjectIssueLabelEventsResponse'
      tags:
        - resource_label_events
  '/groups/{id}/epics/{epic_id}/resource_label_events/{resource_label_event_id}':
    get:
      summary: Get single epic label event
      description: Returns a single label event for a specific group epic
      operationId: getSingleEpicLabelEvent
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group
          required: true
          schema:
            type: string
        - name: epic_id
          in: path
          description: The ID of an epic
          required: true
          schema:
            type: integer
        - name: resource_label_event_id
          in: path
          description: The ID of a label event
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
      tags:
        - resource_label_events
  '/projects/{id}/merge_requests/{merge_request_iid}/resource_label_events':
    get:
      summary: List project merge request label events
      description: Gets a list of all label events for a single merge request.
      operationId: listProjectMergeRequestLabelEvents
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project
          required: true
          schema:
            type: string
        - name: merge_request_iid
          in: path
          description: The IID of a merge request
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listProjectIssueLabelEventsResponse'
      tags:
        - resource_label_events
  '/projects/{id}/merge_requests/{merge_request_iid}/resource_label_events/{resource_label_event_id}':
    get:
      summary: Get single merge request label event
      description: Returns a single label event for a specific project merge request
      operationId: getSingleMergeRequestLabelEvent
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project
          required: true
          schema:
            type: string
        - name: merge_request_iid
          in: path
          description: The IID of a merge request
          required: true
          schema:
            type: integer
        - name: resource_label_event_id
          in: path
          description: The ID of a label event
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
      tags:
        - resource_label_events
components:
  schemas:
    listProjectIssueLabelEventsResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          user:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              username:
                type: string
              state:
                type: string
              avatar_url:
                type: string
              web_url:
                type: string
          created_at:
            type: string
            format: date-time
          resource_type:
            type: string
          resource_id:
            type: integer
          label:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              color:
                type: string
              description:
                type: string
          action:
            type: string
