openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / snippets'
  version: '1.0'
paths:
  /snippets:
    get:
      summary: List all snippets for a user
      description: Get a list of the current user’s snippets.
      operationId: listAllSnippetsForAUser
      parameters: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listAllSnippetsForAUserResponse'
      tags:
        - snippets
    post:
      summary: Create new snippet
      description: Create a new snippet.
      operationId: createNewSnippet
      parameters: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createNewSnippetResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createNewSnippetRequest'
      tags:
        - snippets
  '/snippets/{id}':
    get:
      summary: Get a single snippet
      description: Get a single snippet.
      operationId: getASingleSnippet
      parameters:
        - name: id
          in: path
          description: ID of snippet to retrieve.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getASingleSnippetResponse'
      tags:
        - snippets
    put:
      summary: Update snippet
      description: Update an existing snippet.
      operationId: updateSnippet
      parameters:
        - name: id
          in: path
          description: ID of snippet to update
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updateSnippetResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateSnippetRequest'
      tags:
        - snippets
    delete:
      summary: Delete snippet
      description: Delete an existing snippet.
      operationId: deleteSnippet
      parameters:
        - name: id
          in: path
          description: ID of snippet to delete.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
      tags:
        - snippets
  '/snippets/{id}/raw':
    get:
      summary: Single snippet contents
      description: Get a single snippet’s raw contents.
      operationId: singleSnippetContents
      parameters:
        - name: id
          in: path
          description: ID of snippet to retrieve.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
      tags:
        - snippets
  '/snippets/{id}/files/{ref}/{file_path}/raw':
    get:
      summary: Snippet repository file content
      description: Returns the raw file content as plain text.
      operationId: snippetRepositoryFileContent
      parameters:
        - name: id
          in: path
          description: ID of snippet to retrieve.
          required: true
          schema:
            type: integer
        - name: ref
          in: path
          description: 'Reference to a tag, branch or commit.'
          required: true
          schema:
            type: string
        - name: file_path
          in: path
          description: URL-encoded path to the file.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
      tags:
        - snippets
  /snippets/public:
    get:
      summary: List all public snippets
      description: List all public snippets.
      operationId: listAllPublicSnippets
      parameters:
        - name: per_page
          in: query
          description: Number of snippets to return per page.
          required: false
          schema:
            type: integer
        - name: page
          in: query
          description: Page to retrieve.
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listAllPublicSnippetsResponse'
      tags:
        - snippets
  '/snippets/{id}/user_agent_detail':
    get:
      summary: Get user agent details
      description: ''
      operationId: getUserAgentDetails
      parameters:
        - name: id
          in: path
          description: ID of snippet.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getUserAgentDetailsResponse'
      tags:
        - snippets
components:
  schemas:
    listAllSnippetsForAUserResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          title:
            type: string
          file_name:
            type: string
          description:
            type: string
          visibility:
            type: string
          author:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              username:
                type: string
              state:
                type: string
              avatar_url:
                type: string
              web_url:
                type: string
          updated_at:
            type: string
          created_at:
            type: string
          project_id:
            type: string
          web_url:
            type: string
          raw_url:
            type: string
    getASingleSnippetResponse:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        file_name:
          type: string
        description:
          type: string
        visibility:
          type: string
        author:
          type: object
          properties:
            id:
              type: integer
            username:
              type: string
            email:
              type: string
            name:
              type: string
            state:
              type: string
            created_at:
              type: string
        expires_at:
          type: string
        updated_at:
          type: string
        created_at:
          type: string
        project_id:
          type: string
        web_url:
          type: string
        raw_url:
          type: string
    createNewSnippetRequest:
      type: object
      properties:
        title:
          type: string
        file_name:
          type: string
        content:
          type: string
        description:
          type: string
        visibility:
          type: string
        files:
          type: array
          items:
            type: string
        'files:file_path':
          type: string
        'files:content':
          type: string
      required:
        - title
        - 'files:file_path'
        - 'files:content'
    createNewSnippetResponse:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        visibility:
          type: string
        author:
          type: object
          properties:
            id:
              type: integer
            username:
              type: string
            email:
              type: string
            name:
              type: string
            state:
              type: string
            created_at:
              type: string
        expires_at:
          type: string
        updated_at:
          type: string
        created_at:
          type: string
        project_id:
          type: string
        web_url:
          type: string
        raw_url:
          type: string
        ssh_url_to_repo:
          type: string
        http_url_to_repo:
          type: string
        file_name:
          type: string
        files:
          type: array
          items:
            type: object
            properties:
              content:
                type: string
              file_path:
                type: string
    updateSnippetRequest:
      type: object
      properties:
        title:
          type: string
        file_name:
          type: string
        content:
          type: string
        description:
          type: string
        visibility:
          type: string
        files:
          type: array
          items:
            type: string
        'files:action':
          type: string
        'files:file_path':
          type: string
        'files:previous_path':
          type: string
        'files:content':
          type: string
      required:
        - 'files:action'
    updateSnippetResponse:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        visibility:
          type: string
        author:
          type: object
          properties:
            id:
              type: integer
            username:
              type: string
            email:
              type: string
            name:
              type: string
            state:
              type: string
            created_at:
              type: string
        expires_at:
          type: string
        updated_at:
          type: string
        created_at:
          type: string
        project_id:
          type: string
        web_url:
          type: string
        raw_url:
          type: string
        ssh_url_to_repo:
          type: string
        http_url_to_repo:
          type: string
        file_name:
          type: string
        files:
          type: array
          items:
            type: object
            properties:
              action:
                type: string
              previous_path:
                type: string
              file_path:
                type: string
    listAllPublicSnippetsResponse:
      type: array
      items:
        type: object
        properties:
          author:
            type: object
            properties:
              avatar_url:
                type: string
              id:
                type: integer
              name:
                type: string
              state:
                type: string
              username:
                type: string
              web_url:
                type: string
          created_at:
            type: string
          file_name:
            type: string
          id:
            type: integer
          title:
            type: string
          updated_at:
            type: string
          project_id:
            type: string
          web_url:
            type: string
          raw_url:
            type: string
    getUserAgentDetailsResponse:
      type: object
      properties:
        user_agent:
          type: string
        ip_address:
          type: string
        akismet_submitted:
          type: boolean
