openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / tags'
  version: '1.0'
paths:
  '/projects/{id}/repository/tags':
    get:
      summary: List project repository tags
      description: >-
        Get a list of repository tags from a project, sorted by update date and time in descending order. This endpoint
        can be accessed without authentication if the repository is publicly accessible.
      operationId: listProjectRepositoryTags
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project owned by the authenticated user
          required: true
          schema:
            type: string
        - name: order_by
          in: query
          description: Return tags ordered by name or updated fields. Default is updated
          required: false
          schema:
            type: string
        - name: sort
          in: query
          description: Return tags sorted in asc or desc order. Default is desc
          required: false
          schema:
            type: string
        - name: search
          in: query
          description: >-
            Return list of tags matching the search criteria. You can use ^term and term$ to find tags that begin and
            end with term respectively. No other regular expressions are supported.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listProjectRepositoryTagsResponse'
      tags:
        - tags
    post:
      summary: Create a new tag
      description: Creates a new tag in the repository that points to the supplied ref.
      operationId: createANewTag
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project owned by the authenticated user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getASingleRepositoryTagResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createANewTagRequest'
      tags:
        - tags
  '/projects/{id}/repository/tags/{tag_name}':
    get:
      summary: Get a single repository tag
      description: >-
        Get a specific repository tag determined by its name. This endpoint can be accessed without authentication if
        the repository is publicly accessible.
      operationId: getASingleRepositoryTag
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project owned by the authenticated user
          required: true
          schema:
            type: string
        - name: tag_name
          in: path
          description: The name of the tag
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getASingleRepositoryTagResponse'
      tags:
        - tags
    delete:
      summary: Delete a tag
      description: Deletes a tag of a repository with given name.
      operationId: deleteATag
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project owned by the authenticated user
          required: true
          schema:
            type: string
        - name: tag_name
          in: path
          description: The name of a tag
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
      tags:
        - tags
components:
  schemas:
    listProjectRepositoryTagsResponse:
      type: array
      items:
        type: object
        properties:
          commit:
            type: object
            properties:
              id:
                type: string
              short_id:
                type: string
              title:
                type: string
              created_at:
                type: string
              parent_ids:
                type: array
                items:
                  type: string
              message:
                type: string
              author_name:
                type: string
              author_email:
                type: string
              authored_date:
                type: string
              committer_name:
                type: string
              committer_email:
                type: string
              committed_date:
                type: string
          release:
            type: object
            properties:
              tag_name:
                type: string
              description:
                type: string
          name:
            type: string
          target:
            type: string
          message:
            type: string
          protected:
            type: boolean
    getASingleRepositoryTagResponse:
      type: object
      properties:
        name:
          type: string
        message:
          type: string
        target:
          type: string
        commit:
          type: object
          properties:
            id:
              type: string
            short_id:
              type: string
            title:
              type: string
            created_at:
              type: string
            parent_ids:
              type: array
              items:
                type: string
            message:
              type: string
            author_name:
              type: string
            author_email:
              type: string
            authored_date:
              type: string
            committer_name:
              type: string
            committer_email:
              type: string
            committed_date:
              type: string
        release:
          type: string
        protected:
          type: boolean
    createANewTagRequest:
      type: object
      properties:
        tag_name:
          type: string
        ref:
          type: string
        message:
          type: string
      required:
        - tag_name
        - ref
