openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / topics'
  version: '1.0'
paths:
  /topics:
    get:
      summary: List topics
      description: Returns a list of project topics in the GitLab instance ordered by number of associated projects.
      operationId: listTopics
      parameters:
        - name: page
          in: query
          description: Page to retrieve. Defaults to 1.
          required: false
          schema:
            type: integer
        - name: per_page
          in: query
          description: Number of records to return per page. Defaults to 20.
          required: false
          schema:
            type: integer
        - name: search
          in: query
          description: Search topics against their name.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listTopicsResponse'
      tags:
        - topics
    post:
      summary: Create a project topic
      description: Create a new project topic. Only available to administrators.
      operationId: createAProjectTopic
      parameters: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getATopicResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createAProjectTopicRequest'
      tags:
        - topics
  '/topics/{id}':
    get:
      summary: Get a topic
      description: Get a project topic by ID.
      operationId: getATopic
      parameters:
        - name: id
          in: path
          description: ID of project topic
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getATopicResponse'
      tags:
        - topics
    put:
      summary: Update a project topic
      description: Update a project topic. Only available to administrators.
      operationId: updateAProjectTopic
      parameters:
        - name: id
          in: path
          description: ID of project topic
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getATopicResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createAProjectTopicRequest'
      tags:
        - topics
    delete:
      summary: Delete a project topic
      description: >-
        You must be an administrator to delete a project. When you delete a project topic, you also delete the topic
        assignment for projects.
      operationId: deleteAProjectTopic
      parameters:
        - name: id
          in: path
          description: ID of project topic
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
      tags:
        - topics
  /projects:
    get:
      summary: List projects assigned to a topic
      description: Use the Projects API to list all projects assigned to a specific topic.
      operationId: listProjectsAssignedToATopic
      parameters: []
      responses:
        '200':
          description: successful operation
      tags:
        - topics
components:
  schemas:
    listTopicsResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          name:
            type: string
          description:
            type: string
          total_projects_count:
            type: integer
          avatar_url:
            type: string
    getATopicResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        total_projects_count:
          type: integer
        avatar_url:
          type: string
    createAProjectTopicRequest:
      type: object
      properties:
        name:
          type: string
        avatar:
          type: string
          format: binary
        description:
          type: string
