openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / vulnerabilities'
  version: '1.0'
paths:
  '/vulnerabilities/{id}':
    get:
      summary: Single vulnerability
      description: Gets a single vulnerability
      operationId: singleVulnerability
      parameters:
        - name: id
          in: path
          description: The ID of a Vulnerability to get
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/singleVulnerabilityResponse'
      tags:
        - vulnerabilities
  '/vulnerabilities/{id}/confirm':
    post:
      summary: Confirm vulnerability
      description: Confirms a given vulnerability. Returns status code 304 if the vulnerability is already confirmed.
      operationId: confirmVulnerability
      parameters:
        - name: id
          in: path
          description: The ID of a vulnerability to confirm
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/confirmVulnerabilityResponse'
      tags:
        - vulnerabilities
  '/vulnerabilities/{id}/resolve':
    post:
      summary: Resolve vulnerability
      description: Resolves a given vulnerability. Returns status code 304 if the vulnerability is already resolved.
      operationId: resolveVulnerability
      parameters:
        - name: id
          in: path
          description: The ID of a Vulnerability to resolve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resolveVulnerabilityResponse'
      tags:
        - vulnerabilities
  '/vulnerabilities/{id}/dismiss':
    post:
      summary: Dismiss vulnerability
      description: Dismisses a given vulnerability. Returns status code 304 if the vulnerability is already dismissed.
      operationId: dismissVulnerability
      parameters:
        - name: id
          in: path
          description: The ID of a vulnerability to dismiss
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dismissVulnerabilityResponse'
      tags:
        - vulnerabilities
  '/vulnerabilities/{id}/revert':
    post:
      summary: Revert vulnerability to detected state
      description: >-
        Reverts a given vulnerability to detected state. Returns status code 304 if the vulnerability is already in
        detected state.
      operationId: revertVulnerabilityToDetectedState
      parameters:
        - name: id
          in: path
          description: The ID of a vulnerability to revert to detected state
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/revertVulnerabilityToDetectedStateResponse'
      tags:
        - vulnerabilities
components:
  schemas:
    singleVulnerabilityResponse:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        state:
          type: string
        severity:
          type: string
        confidence:
          type: string
        report_type:
          type: string
        project:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            full_path:
              type: string
            full_name:
              type: string
        author_id:
          type: integer
        updated_by_id:
          type: string
        last_edited_by_id:
          type: string
        closed_by_id:
          type: string
        start_date:
          type: string
        due_date:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
        last_edited_at:
          type: string
        closed_at:
          type: string
    confirmVulnerabilityResponse:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        state:
          type: string
        severity:
          type: string
        confidence:
          type: string
        report_type:
          type: string
        project:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            full_path:
              type: string
            full_name:
              type: string
        author_id:
          type: integer
        updated_by_id:
          type: string
        last_edited_by_id:
          type: string
        closed_by_id:
          type: string
        start_date:
          type: string
        due_date:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
        last_edited_at:
          type: string
        closed_at:
          type: string
    resolveVulnerabilityResponse:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        state:
          type: string
        severity:
          type: string
        confidence:
          type: string
        report_type:
          type: string
        project:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            full_path:
              type: string
            full_name:
              type: string
        author_id:
          type: integer
        updated_by_id:
          type: string
        last_edited_by_id:
          type: string
        closed_by_id:
          type: string
        start_date:
          type: string
        due_date:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
        last_edited_at:
          type: string
        closed_at:
          type: string
    dismissVulnerabilityResponse:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        state:
          type: string
        severity:
          type: string
        confidence:
          type: string
        report_type:
          type: string
        project:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            full_path:
              type: string
            full_name:
              type: string
        author_id:
          type: integer
        updated_by_id:
          type: string
        last_edited_by_id:
          type: string
        closed_by_id:
          type: string
        start_date:
          type: string
        due_date:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
        last_edited_at:
          type: string
        closed_at:
          type: string
    revertVulnerabilityToDetectedStateResponse:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        state:
          type: string
        severity:
          type: string
        confidence:
          type: string
        report_type:
          type: string
        project:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            full_path:
              type: string
            full_name:
              type: string
        author_id:
          type: integer
        updated_by_id:
          type: string
        last_edited_by_id:
          type: string
        closed_by_id:
          type: string
        start_date:
          type: string
        due_date:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
        last_edited_at:
          type: string
        closed_at:
          type: string
