openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / vulnerability_findings'
  version: '1.0'
paths:
  '/projects/{id}/vulnerability_findings':
    get:
      summary: List project vulnerability findings
      description: List all of a project’s vulnerability findings.
      operationId: listProjectVulnerabilityFindings
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project which the authenticated user is a member of.
          required: true
          schema:
            type: string
        - name: report_type
          in: query
          description: >-
            Returns vulnerability findings belonging to specified report type. Valid values: sast, dast,
            dependency_scanning, or container_scanning. Defaults to all.
          required: false
          schema:
            type: string
        - name: scope
          in: query
          description: 'Returns vulnerability findings for the given scope: all or dismissed. Defaults to dismissed.'
          required: false
          schema:
            type: string
        - name: severity
          in: query
          description: >-
            Returns vulnerability findings belonging to specified severity level: info, unknown, low, medium, high, or
            critical. Defaults to all.
          required: false
          schema:
            type: string
        - name: confidence
          in: query
          description: >-
            Returns vulnerability findings belonging to specified confidence level: ignore, unknown, experimental, low,
            medium, high, or confirmed. Defaults to all.
          required: false
          schema:
            type: string
        - name: pipeline_id
          in: query
          description: Returns vulnerability findings belonging to specified pipeline.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listProjectVulnerabilityFindingsResponse'
      tags:
        - vulnerability_findings
components:
  schemas:
    listProjectVulnerabilityFindingsResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
          report_type:
            type: string
          name:
            type: string
          severity:
            type: string
          confidence:
            type: string
          scanner:
            type: object
            properties:
              external_id:
                type: string
              name:
                type: string
              vendor:
                type: string
          identifiers:
            type: array
            items:
              type: object
              properties:
                external_type:
                  type: string
                external_id:
                  type: string
                name:
                  type: string
                url:
                  type: string
          project_fingerprint:
            type: string
          uuid:
            type: string
          create_jira_issue_url:
            type: string
          false_positive:
            type: boolean
          create_vulnerability_feedback_issue_path:
            type: string
          create_vulnerability_feedback_merge_request_path:
            type: string
          create_vulnerability_feedback_dismissal_path:
            type: string
          project:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              full_path:
                type: string
              full_name:
                type: string
          dismissal_feedback:
            type: string
          issue_feedback:
            type: string
          merge_request_feedback:
            type: string
          description:
            type: string
          links:
            type: array
            items: {}
          location:
            type: object
            properties:
              file:
                type: string
              start_line:
                type: integer
              class:
                type: string
              method:
                type: string
          remediations:
            type: array
            items:
              type: string
          solution:
            type: string
          evidence:
            type: string
          request:
            type: string
          response:
            type: string
          evidence_source:
            type: string
          supporting_messages:
            type: array
            items: {}
          assets:
            type: array
            items: {}
          details:
            type: object
            properties: {}
          state:
            type: string
          scan:
            type: object
            properties:
              type:
                type: string
              status:
                type: string
              start_time:
                type: string
              end_time:
                type: string
          blob_path:
            type: string
