openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / group_activity_analytics'
  version: '1.0'
paths:
  /analytics/group_activity/issues_count:
    get:
      summary: Get count of recently created issues for group
      description: ''
      operationId: getCountOfRecentlyCreatedIssuesForGroup
      parameters:
        - name: group_path
          in: query
          description: Group path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getCountOfRecentlyCreatedIssuesForGroupResponse'
      tags:
        - group_activity_analytics
  /analytics/group_activity/merge_requests_count:
    get:
      summary: Get count of recently created merge requests for group
      description: ''
      operationId: getCountOfRecentlyCreatedMergeRequestsForGroup
      parameters:
        - name: group_path
          in: query
          description: Group path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getCountOfRecentlyCreatedMergeRequestsForGroupResponse'
      tags:
        - group_activity_analytics
  /analytics/group_activity/new_members_count:
    get:
      summary: Get count of members recently added to group
      description: ''
      operationId: getCountOfMembersRecentlyAddedToGroup
      parameters:
        - name: group_path
          in: query
          description: Group path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getCountOfMembersRecentlyAddedToGroupResponse'
      tags:
        - group_activity_analytics
components:
  schemas:
    getCountOfRecentlyCreatedIssuesForGroupResponse:
      type: object
      properties:
        issues_count:
          type: integer
    getCountOfRecentlyCreatedMergeRequestsForGroupResponse:
      type: object
      properties:
        merge_requests_count:
          type: integer
    getCountOfMembersRecentlyAddedToGroupResponse:
      type: object
      properties:
        new_members_count:
          type: integer
