openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / vulnerability_exports'
  version: '1.0'
paths:
  '/security/projects/{id}/vulnerability_exports':
    post:
      summary: Create a project-level vulnerability export
      description: Creates a new vulnerability export for a project.
      operationId: createAProjectLevelVulnerabilityExport
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project which the authenticated user is a member of
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createAProjectLevelVulnerabilityExportResponse'
      tags:
        - vulnerability_exports
  '/security/groups/{id}/vulnerability_exports':
    post:
      summary: Create a group-level vulnerability export
      description: Creates a new vulnerability export for a group.
      operationId: createAGroupLevelVulnerabilityExport
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group which the authenticated user is a member of
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createAProjectLevelVulnerabilityExportResponse'
      tags:
        - vulnerability_exports
  /security/vulnerability_exports:
    post:
      summary: Create an instance-level vulnerability export
      description: Creates a new vulnerability export for the projects of the user selected in the Security Dashboard.
      operationId: createAnInstanceLevelVulnerabilityExport
      parameters: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createAProjectLevelVulnerabilityExportResponse'
      tags:
        - vulnerability_exports
  '/security/vulnerability_exports/{id}':
    get:
      summary: Get single vulnerability export
      description: Gets a single vulnerability export.
      operationId: getSingleVulnerabilityExport
      parameters:
        - name: id
          in: path
          description: The vulnerability export’s ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createAProjectLevelVulnerabilityExportResponse'
      tags:
        - vulnerability_exports
  '/security/vulnerability_exports/{id}/download':
    get:
      summary: Download vulnerability export
      description: Downloads a single vulnerability export.
      operationId: downloadVulnerabilityExport
      parameters:
        - name: id
          in: path
          description: The vulnerability export’s ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
      tags:
        - vulnerability_exports
components:
  schemas:
    createAProjectLevelVulnerabilityExportResponse:
      type: object
      properties:
        id:
          type: integer
        created_at:
          type: string
          format: date-time
        project_id:
          type: integer
        group_id:
          type: string
        format:
          type: string
        status:
          type: string
        started_at:
          type: string
        finished_at:
          type: string
        _links:
          type: object
          properties:
            self:
              type: string
            download:
              type: string
