endpoints:
  - /applications:
      post:
        summary: Create an application
        description: Create an application by posting a JSON payload.
        operationId: createAnApplication
        parameters: []
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: integer
                    application_id:
                      type: string
                    application_name:
                      type: string
                    secret:
                      type: string
                    callback_url:
                      type: string
                    confidential:
                      type: boolean
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  redirect_uri:
                    type: string
                  scopes:
                    type: string
                  confidential:
                    type: boolean
                required:
                  - name
                  - redirect_uri
                  - scopes
  - /applications:
      get:
        summary: List all applications
        description: List all registered applications.
        operationId: listAllApplications
        parameters: []
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      application_id:
                        type: string
                      application_name:
                        type: string
                      callback_url:
                        type: string
                      confidential:
                        type: boolean
  - '/applications/{id}':
      delete:
        summary: Delete an application
        description: Delete a specific application.
        operationId: deleteAnApplication
        parameters:
          - name: id
            in: path
            description: The ID of the application (not the application_id).
            required: true
            schema:
              type: integer
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: string
