paths:
  /application/appearance:
    get:
      summary: Get current appearance configuration
      description: List the current appearance configuration of the GitLab instance.
      operationId: getCurrentAppearanceConfiguration
      parameters: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  description:
                    type: string
                  logo:
                    type: string
                  header_logo:
                    type: string
                  favicon:
                    type: string
                  new_project_guidelines:
                    type: string
                  profile_image_guidelines:
                    type: string
                  header_message:
                    type: string
                  footer_message:
                    type: string
                  message_background_color:
                    type: string
                  message_font_color:
                    type: string
                  email_header_and_footer_enabled:
                    type: boolean
    put:
      summary: Change logo
      description: Upload a logo to your GitLab instance.
      operationId: changeLogo
      parameters: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                logo:
                  type: string
              required: []
