paths:
  '/projects/{id}/repository/branches':
    get:
      summary: List repository branches
      description: >-
        Get a list of repository branches from a project, sorted by name
        alphabetically.
      operationId: listRepositoryBranches
      parameters:
        - name: id
          in: path
          description: >-
            ID or URL-encoded path of the project owned by the authenticated
            user.
          required: true
          schema:
            type: string
        - name: search
          in: query
          description: >-
            Return list of branches containing the search string. You can use
            ^term and term$ to find branches that begin and end with term
            respectively.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    merged:
                      type: boolean
                    protected:
                      type: boolean
                    default:
                      type: boolean
                    developers_can_push:
                      type: boolean
                    developers_can_merge:
                      type: boolean
                    can_push:
                      type: boolean
                    web_url:
                      type: string
                    commit:
                      type: object
                      properties:
                        author_email:
                          type: string
                        author_name:
                          type: string
                        authored_date:
                          type: string
                        committed_date:
                          type: string
                        committer_email:
                          type: string
                        committer_name:
                          type: string
                        id:
                          type: string
                        short_id:
                          type: string
                        title:
                          type: string
                        message:
                          type: string
                        parent_ids:
                          type: array
                          items:
                            type: string
    post:
      summary: Create repository branch
      description: Create a new branch in the repository.
      operationId: createRepositoryBranch
      parameters:
        - name: id
          in: path
          description: >-
            ID or URL-encoded path of the project owned by the authenticated
            user.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  commit:
                    type: object
                    properties:
                      author_email:
                        type: string
                      author_name:
                        type: string
                      authored_date:
                        type: string
                      committed_date:
                        type: string
                      committer_email:
                        type: string
                      committer_name:
                        type: string
                      id:
                        type: string
                      short_id:
                        type: string
                      title:
                        type: string
                      message:
                        type: string
                      parent_ids:
                        type: array
                        items:
                          type: string
                  name:
                    type: string
                  merged:
                    type: boolean
                  protected:
                    type: boolean
                  default:
                    type: boolean
                  developers_can_push:
                    type: boolean
                  developers_can_merge:
                    type: boolean
                  can_push:
                    type: boolean
                  web_url:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                branch:
                  type: string
                ref:
                  type: string
              required:
                - branch
                - ref
  '/projects/{id}/repository/branches/{branch}':
    get:
      summary: Get single repository branch
      description: Get a single project repository branch.
      operationId: getSingleRepositoryBranch
      parameters:
        - name: id
          in: path
          description: >-
            ID or URL-encoded path of the project owned by the authenticated
            user.
          required: true
          schema:
            type: string
        - name: branch
          in: path
          description: Name of the branch.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  merged:
                    type: boolean
                  protected:
                    type: boolean
                  default:
                    type: boolean
                  developers_can_push:
                    type: boolean
                  developers_can_merge:
                    type: boolean
                  can_push:
                    type: boolean
                  web_url:
                    type: string
                  commit:
                    type: object
                    properties:
                      author_email:
                        type: string
                      author_name:
                        type: string
                      authored_date:
                        type: string
                      committed_date:
                        type: string
                      committer_email:
                        type: string
                      committer_name:
                        type: string
                      id:
                        type: string
                      short_id:
                        type: string
                      title:
                        type: string
                      message:
                        type: string
                      parent_ids:
                        type: array
                        items:
                          type: string
    delete:
      summary: Delete repository branch
      description: Delete a branch from the repository.
      operationId: deleteRepositoryBranch
      parameters:
        - name: id
          in: path
          description: >-
            ID or URL-encoded path of the project owned by the authenticated
            user.
          required: true
          schema:
            type: string
        - name: branch
          in: path
          description: Name of the branch.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: string
  '/projects/{id}/repository/merged_branches':
    delete:
      summary: Delete merged branches
      description: Deletes all branches that are merged into the project’s default branch.
      operationId: deleteMergedBranches
      parameters:
        - name: id
          in: path
          description: >-
            ID or URL-encoded path of the project owned by the authenticated
            user.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: string
