paths:
  /deploy_keys:
    get:
      summary: List all deploy keys
      description: >-
        Get a list of all deploy keys across all projects of the GitLab
        instance. This endpoint requires administrator access and is not
        available on GitLab.com.
      operationId: listAllDeployKeys
      parameters:
        - name: public
          in: query
          description: Only return deploy keys that are public. Defaults to false.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    key:
                      type: string
                    fingerprint:
                      type: string
                    created_at:
                      type: string
                    projects_with_write_access:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                          description:
                            type: string
                          name:
                            type: string
                          name_with_namespace:
                            type: string
                          path:
                            type: string
                          path_with_namespace:
                            type: string
                          created_at:
                            type: string
  '/projects/{id}/deploy_keys':
    get:
      summary: List project deploy keys
      description: Get a list of a project’s deploy keys.
      operationId: listProjectDeployKeys
      parameters:
        - name: id
          in: path
          description: >-
            The ID or URL-encoded path of the project owned by the authenticated
            user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    key:
                      type: string
                    created_at:
                      type: string
                    can_push:
                      type: boolean
    post:
      summary: Add deploy key
      description: Creates a new deploy key for a project.
      operationId: addDeployKey
      parameters:
        - name: id
          in: path
          description: >-
            The ID or URL-encoded path of the project owned by the authenticated
            user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    type: string
                  id:
                    type: integer
                  title:
                    type: string
                  can_push:
                    type: boolean
                  created_at:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                key:
                  type: string
                can_push:
                  type: boolean
              required:
                - title
                - key
  '/projects/{id}/deploy_keys/{key_id}':
    get:
      summary: Get a single deploy key
      description: Get a single key.
      operationId: getASingleDeployKey
      parameters:
        - name: id
          in: path
          description: >-
            The ID or URL-encoded path of the project owned by the authenticated
            user
          required: true
          schema:
            type: string
        - name: key_id
          in: path
          description: The ID of the deploy key
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  key:
                    type: string
                  created_at:
                    type: string
                  can_push:
                    type: boolean
    put:
      summary: Update deploy key
      description: Updates a deploy key for a project.
      operationId: updateDeployKey
      parameters:
        - name: id
          in: path
          description: >-
            The ID or URL-encoded path of the project owned by the authenticated
            user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  key:
                    type: string
                  created_at:
                    type: string
                  can_push:
                    type: boolean
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                can_push:
                  type: boolean
              required: []
    delete:
      summary: Delete deploy key
      description: >-
        Removes a deploy key from the project. If the deploy key is used only
        for this project, it’s deleted from the system.
      operationId: deleteDeployKey
      parameters:
        - name: id
          in: path
          description: >-
            The ID or URL-encoded path of the project owned by the authenticated
            user
          required: true
          schema:
            type: string
        - name: key_id
          in: path
          description: The ID of the deploy key
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: string
