endpoints:
  - '/projects/{id}/freeze_periods':
      get:
        summary: List Freeze Periods
        description: >-
          Paginated list of Freeze Periods, sorted by created_at in ascending
          order.
        operationId: listFreezePeriods
        parameters:
          - name: id
            in: path
            description: The ID or URL-encoded path of the project.
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      freeze_start:
                        type: string
                      freeze_end:
                        type: string
                      cron_timezone:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
  - '/projects/{id}/freeze_periods/{freeze_period_id}':
      get:
        summary: Get a Freeze Period by a freeze_period_id
        description: Get a Freeze Period for the given freeze_period_id.
        operationId: getAFreezePeriodByAFreeze_period_id
        parameters:
          - name: id
            in: path
            description: The ID or URL-encoded path of the project.
            required: true
            schema:
              type: string
          - name: freeze_period_id
            in: path
            description: The database ID of the Freeze Period.
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: integer
                    freeze_start:
                      type: string
                    freeze_end:
                      type: string
                    cron_timezone:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
  - '/projects/{id}/freeze_periods':
      post:
        summary: Create a Freeze Period
        description: Create a Freeze Period.
        operationId: createAFreezePeriod
        parameters:
          - name: id
            in: path
            description: The ID or URL-encoded path of the project.
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: integer
                    freeze_start:
                      type: string
                    freeze_end:
                      type: string
                    cron_timezone:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  freeze_start:
                    type: string
                  freeze_end:
                    type: string
                  cron_timezone:
                    type: string
                required:
                  - freeze_start
                  - freeze_end
  - '/projects/{id}/freeze_periods/{freeze_period_id}':
      put:
        summary: Update a Freeze Period
        description: Update a Freeze Period for the given freeze_period_id.
        operationId: updateAFreezePeriod
        parameters:
          - name: id
            in: path
            description: The ID or URL-encoded path of the project.
            required: true
            schema:
              type: string
          - name: freeze_period_id
            in: path
            description: The database ID of the Freeze Period.
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: integer
                    freeze_start:
                      type: string
                    freeze_end:
                      type: string
                    cron_timezone:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  freeze_start:
                    type: string
                  freeze_end:
                    type: string
                  cron_timezone:
                    type: string
                required: []
  - '/projects/{id}/freeze_periods/{freeze_period_id}':
      delete:
        summary: Delete a Freeze Period
        description: Delete a Freeze Period for the given freeze_period_id.
        operationId: deleteAFreezePeriod
        parameters:
          - name: id
            in: path
            description: The ID or URL-encoded path of the project.
            required: true
            schema:
              type: string
          - name: freeze_period_id
            in: path
            description: The database ID of the Freeze Period.
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: string
