endpoints:
  - '/groups/{id}/variables':
      get:
        summary: List group variables
        description: Get list of a group’s variables.
        operationId: listGroupVariables
        parameters:
          - name: id
            in: path
            description: >-
              The ID of a group or URL-encoded path of the group owned by the
              authenticated user
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                      variable_type:
                        type: string
                      value:
                        type: string
                      protected:
                        type: boolean
                      masked:
                        type: boolean
                      environment_scope:
                        type: string
  - '/groups/{id}/variables/{key}':
      get:
        summary: Show variable details
        description: Get the details of a group’s specific variable.
        operationId: showVariableDetails
        parameters:
          - name: id
            in: path
            description: >-
              The ID of a group or URL-encoded path of the group owned by the
              authenticated user
            required: true
            schema:
              type: string
          - name: key
            in: path
            description: The key of a variable
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    key:
                      type: string
                    variable_type:
                      type: string
                    value:
                      type: string
                    protected:
                      type: boolean
                    masked:
                      type: boolean
                    environment_scope:
                      type: string
  - '/groups/{id}/variables':
      post:
        summary: Create variable
        description: Create a new variable.
        operationId: createVariable
        parameters:
          - name: id
            in: path
            description: >-
              The ID of a group or URL-encoded path of the group owned by the
              authenticated user
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    key:
                      type: string
                    value:
                      type: string
                    variable_type:
                      type: string
                    protected:
                      type: boolean
                    masked:
                      type: boolean
                    environment_scope:
                      type: string
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    type: string
                  value:
                    type: string
                  variable_type:
                    type: string
                  protected:
                    type: boolean
                  masked:
                    type: boolean
                  environment_scope:
                    type: string
                required:
                  - key
                  - value
  - '/groups/{id}/variables/{key}':
      put:
        summary: Update variable
        description: Update a group’s variable.
        operationId: updateVariable
        parameters:
          - name: id
            in: path
            description: >-
              The ID of a group or URL-encoded path of the group owned by the
              authenticated user
            required: true
            schema:
              type: string
          - name: key
            in: path
            description: The key of a variable
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    key:
                      type: string
                    value:
                      type: string
                    variable_type:
                      type: string
                    protected:
                      type: boolean
                    masked:
                      type: boolean
                    environment_scope:
                      type: string
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: string
                  variable_type:
                    type: string
                  protected:
                    type: boolean
                  masked:
                    type: boolean
                  environment_scope:
                    type: string
                required:
                  - value
  - '/groups/{id}/variables/{key}':
      delete:
        summary: Remove variable
        description: Remove a group’s variable.
        operationId: removeVariable
        parameters:
          - name: id
            in: path
            description: >-
              The ID of a group or URL-encoded path of the group owned by the
              authenticated user
            required: true
            schema:
              type: string
          - name: key
            in: path
            description: The key of a variable
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: string
