endpoints:
  - /admin/ci/variables:
      get:
        summary: List all instance variables
        description: Get the list of all instance-level variables.
        operationId: listAllInstanceVariables
        parameters: []
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                      variable_type:
                        type: string
                      value:
                        type: string
                      protected:
                        type: boolean
                      masked:
                        type: boolean
  - '/admin/ci/variables/{key}':
      get:
        summary: Show instance variable details
        description: Get the details of a specific instance-level variable.
        operationId: showInstanceVariableDetails
        parameters:
          - name: key
            in: path
            description: The key of a variable
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    key:
                      type: string
                    variable_type:
                      type: string
                    value:
                      type: string
                    protected:
                      type: boolean
                    masked:
                      type: boolean
  - /admin/ci/variables:
      post:
        summary: Create instance variable
        description: Create a new instance-level variable.
        operationId: createInstanceVariable
        parameters: []
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    key:
                      type: string
                    value:
                      type: string
                    variable_type:
                      type: string
                    protected:
                      type: boolean
                    masked:
                      type: boolean
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    type: string
                  value:
                    type: string
                  variable_type:
                    type: string
                  protected:
                    type: boolean
                  masked:
                    type: boolean
                required:
                  - key
                  - value
  - '/admin/ci/variables/{key}':
      put:
        summary: Update instance variable
        description: Update an instance-level variable.
        operationId: updateInstanceVariable
        parameters:
          - name: key
            in: path
            description: The key of a variable.
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    key:
                      type: string
                    value:
                      type: string
                    variable_type:
                      type: string
                    protected:
                      type: boolean
                    masked:
                      type: boolean
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: string
                  variable_type:
                    type: string
                  protected:
                    type: boolean
                  masked:
                    type: boolean
                required:
                  - value
  - '/admin/ci/variables/{key}':
      delete:
        summary: Remove instance variable
        description: Remove an instance-level variable.
        operationId: removeInstanceVariable
        parameters:
          - name: key
            in: path
            description: The key of a variable
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: string
