paths:
  /issues_statistics:
    get:
      summary: Get issues statistics
      description: >-
        Gets issues count statistics on all issues the authenticated user has
        access to. By default it returns only issues created by the current
        user. To get all issues, use parameter scope=all.
      operationId: getIssuesStatistics
      parameters:
        - name: labels
          in: query
          description: >-
            Comma-separated list of label names, issues must have all labels to
            be returned. None lists all issues with no labels. Any lists all
            issues with at least one label.
          required: false
          schema:
            type: string
        - name: milestone
          in: query
          description: >-
            The milestone title. None lists all issues with no milestone. Any
            lists all issues that have an assigned milestone.
          required: false
          schema:
            type: string
        - name: scope
          in: query
          description: >-
            Return issues for the given scope: created_by_me, assigned_to_me or
            all. Defaults to created_by_me
          required: false
          schema:
            type: string
        - name: author_id
          in: query
          description: >-
            Return issues created by the given user id. Mutually exclusive with
            author_username. Combine with scope=all or scope=assigned_to_me.
          required: false
          schema:
            type: integer
        - name: author_username
          in: query
          description: >-
            Return issues created by the given username. Similar to author_id
            and mutually exclusive with author_id.
          required: false
          schema:
            type: string
        - name: assignee_id
          in: query
          description: >-
            Return issues assigned to the given user id. Mutually exclusive with
            assignee_username. None returns unassigned issues. Any returns
            issues with an assignee.
          required: false
          schema:
            type: integer
        - name: assignee_username
          in: query
          description: >-
            Return issues assigned to the given username. Similar to assignee_id
            and mutually exclusive with assignee_id. In GitLab CE
            assignee_username array should only contain a single value or an
            invalid parameter error is returned otherwise.
          required: false
          schema:
            type: string
        - name: epic_id
          in: query
          description: >-
            Return issues associated with the given epic ID. None returns issues
            that are not associated with an epic. Any returns issues that are
            associated with an epic. (Introduced in GitLab 13.6)
          required: false
          schema:
            type: integer
        - name: my_reaction_emoji
          in: query
          description: >-
            Return issues reacted by the authenticated user by the given emoji.
            None returns issues not given a reaction. Any returns issues given
            at least one reaction.
          required: false
          schema:
            type: string
        - name: 'iids[]'
          in: query
          description: Return only the issues having the given iid
          required: false
          schema:
            type: string
        - name: search
          in: query
          description: Search issues against their title and description
          required: false
          schema:
            type: string
        - name: in
          in: query
          description: >-
            Modify the scope of the search attribute. title, description, or a
            string joining them with comma. Default is title,description
          required: false
          schema:
            type: string
        - name: created_after
          in: query
          description: >-
            Return issues created on or after the given time. Expected in ISO
            8601 format (2019-03-15T08:00:00Z)
          required: false
          schema:
            type: string
        - name: created_before
          in: query
          description: >-
            Return issues created on or before the given time. Expected in ISO
            8601 format (2019-03-15T08:00:00Z)
          required: false
          schema:
            type: string
        - name: updated_after
          in: query
          description: >-
            Return issues updated on or after the given time. Expected in ISO
            8601 format (2019-03-15T08:00:00Z)
          required: false
          schema:
            type: string
        - name: updated_before
          in: query
          description: >-
            Return issues updated on or before the given time. Expected in ISO
            8601 format (2019-03-15T08:00:00Z)
          required: false
          schema:
            type: string
        - name: confidential
          in: query
          description: Filter confidential or public issues.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  statistics:
                    type: object
                    properties:
                      counts:
                        type: object
                        properties:
                          all:
                            type: integer
                          closed:
                            type: integer
                          opened:
                            type: integer
  '/groups/{id}/issues_statistics':
    get:
      summary: Get group issues statistics
      description: Gets issues count statistics for given group.
      operationId: getGroupIssuesStatistics
      parameters:
        - name: id
          in: path
          description: >-
            The ID or URL-encoded path of the group owned by the authenticated
            user
          required: true
          schema:
            type: string
        - name: labels
          in: query
          description: >-
            Comma-separated list of label names, issues must have all labels to
            be returned. None lists all issues with no labels. Any lists all
            issues with at least one label.
          required: false
          schema:
            type: string
        - name: 'iids[]'
          in: query
          description: Return only the issues having the given iid
          required: false
          schema:
            type: string
        - name: milestone
          in: query
          description: >-
            The milestone title. None lists all issues with no milestone. Any
            lists all issues that have an assigned milestone.
          required: false
          schema:
            type: string
        - name: scope
          in: query
          description: >-
            Return issues for the given scope: created_by_me, assigned_to_me or
            all.
          required: false
          schema:
            type: string
        - name: author_id
          in: query
          description: >-
            Return issues created by the given user id. Mutually exclusive with
            author_username. Combine with scope=all or scope=assigned_to_me.
          required: false
          schema:
            type: integer
        - name: author_username
          in: query
          description: >-
            Return issues created by the given username. Similar to author_id
            and mutually exclusive with author_id.
          required: false
          schema:
            type: string
        - name: assignee_id
          in: query
          description: >-
            Return issues assigned to the given user id. Mutually exclusive with
            assignee_username. None returns unassigned issues. Any returns
            issues with an assignee.
          required: false
          schema:
            type: integer
        - name: assignee_username
          in: query
          description: >-
            Return issues assigned to the given username. Similar to assignee_id
            and mutually exclusive with assignee_id. In GitLab CE
            assignee_username array should only contain a single value or an
            invalid parameter error is returned otherwise.
          required: false
          schema:
            type: string
        - name: my_reaction_emoji
          in: query
          description: >-
            Return issues reacted by the authenticated user by the given emoji.
            None returns issues not given a reaction. Any returns issues given
            at least one reaction.
          required: false
          schema:
            type: string
        - name: search
          in: query
          description: Search group issues against their title and description
          required: false
          schema:
            type: string
        - name: created_after
          in: query
          description: >-
            Return issues created on or after the given time. Expected in ISO
            8601 format (2019-03-15T08:00:00Z)
          required: false
          schema:
            type: string
        - name: created_before
          in: query
          description: >-
            Return issues created on or before the given time. Expected in ISO
            8601 format (2019-03-15T08:00:00Z)
          required: false
          schema:
            type: string
        - name: updated_after
          in: query
          description: >-
            Return issues updated on or after the given time. Expected in ISO
            8601 format (2019-03-15T08:00:00Z)
          required: false
          schema:
            type: string
        - name: updated_before
          in: query
          description: >-
            Return issues updated on or before the given time. Expected in ISO
            8601 format (2019-03-15T08:00:00Z)
          required: false
          schema:
            type: string
        - name: confidential
          in: query
          description: Filter confidential or public issues.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  statistics:
                    type: object
                    properties:
                      counts:
                        type: object
                        properties:
                          all:
                            type: integer
                          closed:
                            type: integer
                          opened:
                            type: integer
  '/projects/{id}/issues_statistics':
    get:
      summary: Get project issues statistics
      description: Gets issues count statistics for given project.
      operationId: getProjectIssuesStatistics
      parameters:
        - name: id
          in: path
          description: >-
            The ID or URL-encoded path of the project owned by the authenticated
            user
          required: true
          schema:
            type: string
        - name: 'iids[]'
          in: query
          description: Return only the milestone having the given iid
          required: false
          schema:
            type: string
        - name: labels
          in: query
          description: >-
            Comma-separated list of label names, issues must have all labels to
            be returned. None lists all issues with no labels. Any lists all
            issues with at least one label.
          required: false
          schema:
            type: string
        - name: milestone
          in: query
          description: >-
            The milestone title. None lists all issues with no milestone. Any
            lists all issues that have an assigned milestone.
          required: false
          schema:
            type: string
        - name: scope
          in: query
          description: >-
            Return issues for the given scope: created_by_me, assigned_to_me or
            all.
          required: false
          schema:
            type: string
        - name: author_id
          in: query
          description: >-
            Return issues created by the given user id. Mutually exclusive with
            author_username. Combine with scope=all or scope=assigned_to_me.
          required: false
          schema:
            type: integer
        - name: author_username
          in: query
          description: >-
            Return issues created by the given username. Similar to author_id
            and mutually exclusive with author_id.
          required: false
          schema:
            type: string
        - name: assignee_id
          in: query
          description: >-
            Return issues assigned to the given user id. Mutually exclusive with
            assignee_username. None returns unassigned issues. Any returns
            issues with an assignee.
          required: false
          schema:
            type: integer
        - name: assignee_username
          in: query
          description: >-
            Return issues assigned to the given username. Similar to assignee_id
            and mutually exclusive with assignee_id. In GitLab CE
            assignee_username array should only contain a single value or an
            invalid parameter error is returned otherwise.
          required: false
          schema:
            type: string
        - name: my_reaction_emoji
          in: query
          description: >-
            Return issues reacted by the authenticated user by the given emoji.
            None returns issues not given a reaction. Any returns issues given
            at least one reaction.
          required: false
          schema:
            type: string
        - name: search
          in: query
          description: Search project issues against their title and description
          required: false
          schema:
            type: string
        - name: created_after
          in: query
          description: >-
            Return issues created on or after the given time. Expected in ISO
            8601 format (2019-03-15T08:00:00Z)
          required: false
          schema:
            type: string
        - name: created_before
          in: query
          description: >-
            Return issues created on or before the given time. Expected in ISO
            8601 format (2019-03-15T08:00:00Z)
          required: false
          schema:
            type: string
        - name: updated_after
          in: query
          description: >-
            Return issues updated on or after the given time. Expected in ISO
            8601 format (2019-03-15T08:00:00Z)
          required: false
          schema:
            type: string
        - name: updated_before
          in: query
          description: >-
            Return issues updated on or before the given time. Expected in ISO
            8601 format (2019-03-15T08:00:00Z)
          required: false
          schema:
            type: string
        - name: confidential
          in: query
          description: Filter confidential or public issues.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  statistics:
                    type: object
                    properties:
                      counts:
                        type: object
                        properties:
                          all:
                            type: integer
                          closed:
                            type: integer
                          opened:
                            type: integer
