endpoints:
  - '/projects/{id}/labels':
      get:
        summary: List labels
        description: Get all labels for a given project.
        operationId: listLabels
        parameters:
          - name: id
            in: path
            description: >-
              The ID or URL-encoded path of the project owned by the
              authenticated user
            required: true
            schema:
              type: string
          - name: with_counts
            in: query
            description: >-
              Whether or not to include issue and merge request counts. Defaults
              to false. (Introduced in GitLab 12.2)
            required: false
            schema:
              type: string
          - name: include_ancestor_groups
            in: query
            description: Include ancestor groups. Defaults to true.
            required: false
            schema:
              type: string
          - name: search
            in: query
            description: Keyword to filter labels by. Introduced in GitLab 13.6
            required: false
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      color:
                        type: string
                      text_color:
                        type: string
                      description:
                        type: string
                      description_html:
                        type: string
                      open_issues_count:
                        type: integer
                      closed_issues_count:
                        type: integer
                      open_merge_requests_count:
                        type: integer
                      subscribed:
                        type: boolean
                      priority:
                        type: integer
                      is_project_label:
                        type: boolean
  - '/projects/{id}/labels/{label_id}':
      get:
        summary: Get a single project label
        description: Get a single label for a given project.
        operationId: getASingleProjectLabel
        parameters:
          - name: id
            in: path
            description: >-
              The ID or URL-encoded path of the project owned by the
              authenticated user
            required: true
            schema:
              type: string
          - name: label_id
            in: path
            description: The ID or title of a project’s label.
            required: true
            schema:
              type: string
          - name: include_ancestor_groups
            in: query
            description: Include ancestor groups. Defaults to true.
            required: false
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    color:
                      type: string
                    text_color:
                      type: string
                    description:
                      type: string
                    description_html:
                      type: string
                    open_issues_count:
                      type: integer
                    closed_issues_count:
                      type: integer
                    open_merge_requests_count:
                      type: integer
                    subscribed:
                      type: boolean
                    priority:
                      type: integer
                    is_project_label:
                      type: boolean
  - '/projects/{id}/labels':
      post:
        summary: Create a new label
        description: >-
          Creates a new label for the given repository with the given name and
          color.
        operationId: createANewLabel
        parameters:
          - name: id
            in: path
            description: >-
              The ID or URL-encoded path of the project owned by the
              authenticated user
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    color:
                      type: string
                    text_color:
                      type: string
                    description:
                      type: string
                    description_html:
                      type: string
                    open_issues_count:
                      type: integer
                    closed_issues_count:
                      type: integer
                    open_merge_requests_count:
                      type: integer
                    subscribed:
                      type: boolean
                    priority:
                      type: string
                    is_project_label:
                      type: boolean
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  color:
                    type: string
                  description:
                    type: string
                  priority:
                    type: integer
                required:
                  - name
                  - color
  - '/projects/{id}/labels/{label_id}':
      delete:
        summary: Delete a label
        description: Deletes a label with a given name.
        operationId: deleteALabel
        parameters:
          - name: id
            in: path
            description: >-
              The ID or URL-encoded path of the project owned by the
              authenticated user
            required: true
            schema:
              type: string
          - name: label_id
            in: path
            description: The ID or title of a group’s label.
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: string
  - '/projects/{id}/labels/{label_id}':
      put:
        summary: Edit an existing label
        description: >-
          Updates an existing label with new name or new color. At least one
          parameter is required, to update the label.
        operationId: editAnExistingLabel
        parameters:
          - name: id
            in: path
            description: >-
              The ID or URL-encoded path of the project owned by the
              authenticated user
            required: true
            schema:
              type: string
          - name: label_id
            in: path
            description: The ID or title of a group’s label.
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    color:
                      type: string
                    text_color:
                      type: string
                    description:
                      type: string
                    description_html:
                      type: string
                    open_issues_count:
                      type: integer
                    closed_issues_count:
                      type: integer
                    open_merge_requests_count:
                      type: integer
                    subscribed:
                      type: boolean
                    priority:
                      type: string
                    is_project_label:
                      type: boolean
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  new_name:
                    type: string
                  color:
                    type: string
                  description:
                    type: string
                  priority:
                    type: integer
                required: []
  - '/projects/{id}/labels/{label_id}/promote':
      put:
        summary: Promote a project label to a group label
        description: Promotes a project label to a group label. The label keeps its ID.
        operationId: promoteAProjectLabelToAGroupLabel
        parameters:
          - name: id
            in: path
            description: >-
              The ID or URL-encoded path of the project owned by the
              authenticated user
            required: true
            schema:
              type: string
          - name: label_id
            in: path
            description: The ID or title of a group’s label.
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    color:
                      type: string
                    description:
                      type: string
                    description_html:
                      type: string
                    open_issues_count:
                      type: integer
                    closed_issues_count:
                      type: integer
                    open_merge_requests_count:
                      type: integer
                    subscribed:
                      type: boolean
  - '/projects/{id}/labels/{label_id}/subscribe':
      post:
        summary: Subscribe to a label
        description: >-
          Subscribes the authenticated user to a label to receive notifications.
          If the user is already subscribed to the label, the status code 304 is
          returned.
        operationId: subscribeToALabel
        parameters:
          - name: id
            in: path
            description: >-
              The ID or URL-encoded path of the project owned by the
              authenticated user
            required: true
            schema:
              type: string
          - name: label_id
            in: path
            description: The ID or title of a project’s label
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    color:
                      type: string
                    text_color:
                      type: string
                    description:
                      type: string
                    description_html:
                      type: string
                    open_issues_count:
                      type: integer
                    closed_issues_count:
                      type: integer
                    open_merge_requests_count:
                      type: integer
                    subscribed:
                      type: boolean
                    priority:
                      type: string
                    is_project_label:
                      type: boolean
  - '/projects/{id}/labels/{label_id}/unsubscribe':
      post:
        summary: Unsubscribe from a label
        description: >-
          Unsubscribes the authenticated user from a label to not receive
          notifications from it. If the user is not subscribed to the label, the
          status code 304 is returned.
        operationId: unsubscribeFromALabel
        parameters:
          - name: id
            in: path
            description: >-
              The ID or URL-encoded path of the project owned by the
              authenticated user
            required: true
            schema:
              type: string
          - name: label_id
            in: path
            description: The ID or title of a project’s label
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: string
