endpoints:
  - /markdown:
      post:
        summary: Render an arbitrary Markdown document
        description: 'Response example:'
        operationId: renderAnArbitraryMarkdownDocument
        parameters: []
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    html:
                      type: string
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string
                  gfm:
                    type: boolean
                  project:
                    type: string
                required:
                  - text
