paths:
  /namespaces:
    get:
      summary: List namespaces
      description: >-
        Get a list of the namespaces of the authenticated user. If the user is
        an administrator, a list of all namespaces in the GitLab instance is
        shown.
      operationId: listNamespaces
      parameters:
        - name: search
          in: query
          description: >-
            Returns a list of namespaces the user is authorized to view based on
            the search criteria
          required: false
          schema:
            type: string
        - name: owned_only
          in: query
          description: 'In GitLab 14.2 and later, returns a list of owned namespaces only'
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    billable_members_count:
                      type: integer
                    max_seats_used:
                      type: integer
                    seats_in_use:
                      type: integer
  '/namespaces/{id}':
    get:
      summary: Get namespace by ID
      description: Get a namespace by ID.
      operationId: getNamespaceById
      parameters:
        - name: id
          in: path
          description: ID or URL-encoded path of the namespace
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  path:
                    type: string
                  kind:
                    type: string
                  full_path:
                    type: string
                  parent_id:
                    type: string
                  avatar_url:
                    type: string
                  web_url:
                    type: string
                  members_count_with_descendants:
                    type: integer
                  billable_members_count:
                    type: integer
                  max_seats_used:
                    type: integer
                  seats_in_use:
                    type: integer
                  plan:
                    type: string
                  trial_ends_on:
                    type: string
                  trial:
                    type: boolean
  '/namespaces/{namespace}/exists':
    get:
      summary: Get existence of a namespace
      description: >-
        Get existence of a namespace by path. Suggests a new namespace path that
        does not already exist.
      operationId: getExistenceOfANamespace
      parameters:
        - name: namespace
          in: path
          description: Namespace’s path.
          required: true
          schema:
            type: string
        - name: parent_id
          in: query
          description: >-
            The ID of the parent namespace. If no ID is specified, only
            top-level namespaces are considered.
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  exists:
                    type: boolean
                  suggests:
                    type: array
                    items:
                      type: string
