endpoints:
  - '/projects/{id}/snippets':
      get:
        summary: List snippets
        description: Get a list of project snippets.
        operationId: listSnippets
        parameters:
          - name: id
            in: path
            description: >-
              The ID or URL-encoded path of the project owned by the
              authenticated user
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: string
  - '/projects/{id}/snippets/{snippet_id}':
      get:
        summary: Single snippet
        description: Get a single project snippet.
        operationId: singleSnippet
        parameters:
          - name: id
            in: path
            description: >-
              The ID or URL-encoded path of the project owned by the
              authenticated user
            required: true
            schema:
              type: string
          - name: snippet_id
            in: path
            description: The ID of a project’s snippet
            required: true
            schema:
              type: integer
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    file_name:
                      type: string
                    description:
                      type: string
                    author:
                      type: object
                      properties:
                        id:
                          type: integer
                        username:
                          type: string
                        email:
                          type: string
                        name:
                          type: string
                        state:
                          type: string
                        created_at:
                          type: string
                    updated_at:
                      type: string
                    created_at:
                      type: string
                    project_id:
                      type: integer
                    web_url:
                      type: string
                    raw_url:
                      type: string
  - '/projects/{id}/snippets':
      post:
        summary: Create new snippet
        description: >-
          Creates a new project snippet. The user must have permission to create
          new snippets.
        operationId: createNewSnippet
        parameters:
          - name: id
            in: path
            description: >-
              The ID or URL-encoded path of the project owned by the
              authenticated user
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    title:
                      type: string
                    description:
                      type: string
                    visibility:
                      type: string
                    files:
                      type: array
                      items:
                        type: object
                        properties:
                          file_path:
                            type: string
                          content:
                            type: string
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  file_name:
                    type: string
                  content:
                    type: string
                  description:
                    type: string
                  visibility:
                    type: string
                  files:
                    type: array
                    items:
                      type: string
                  'files:file_path':
                    type: string
                  'files:content':
                    type: string
                required:
                  - title
                  - 'files:file_path'
                  - 'files:content'
  - '/projects/{id}/snippets/{snippet_id}':
      put:
        summary: Update snippet
        description: >-
          Updates an existing project snippet. The user must have permission to
          change an existing snippet.
        operationId: updateSnippet
        parameters:
          - name: id
            in: path
            description: >-
              The ID or URL-encoded path of the project owned by the
              authenticated user
            required: true
            schema:
              type: string
          - name: snippet_id
            in: path
            description: The ID of a project’s snippet
            required: true
            schema:
              type: integer
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    title:
                      type: string
                    description:
                      type: string
                    visibility:
                      type: string
                    files:
                      type: array
                      items:
                        type: object
                        properties:
                          action:
                            type: string
                          file_path:
                            type: string
                          content:
                            type: string
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  file_name:
                    type: string
                  content:
                    type: string
                  description:
                    type: string
                  visibility:
                    type: string
                  files:
                    type: array
                    items:
                      type: string
                  'files:action':
                    type: string
                  'files:file_path':
                    type: string
                  'files:previous_path':
                    type: string
                  'files:content':
                    type: string
                required:
                  - 'files:action'
  - '/projects/{id}/snippets/{snippet_id}':
      delete:
        summary: Delete snippet
        description: >-
          Deletes an existing project snippet. This returns a 204 No Content
          status code if the operation was successfully or 404 if the resource
          was not found.
        operationId: deleteSnippet
        parameters:
          - name: id
            in: path
            description: >-
              The ID or URL-encoded path of the project owned by the
              authenticated user
            required: true
            schema:
              type: string
          - name: snippet_id
            in: path
            description: The ID of a project’s snippet
            required: true
            schema:
              type: integer
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: string
  - '/projects/{id}/snippets/{snippet_id}/raw':
      get:
        summary: Snippet content
        description: Returns the raw project snippet as plain text.
        operationId: snippetContent
        parameters:
          - name: id
            in: path
            description: >-
              The ID or URL-encoded path of the project owned by the
              authenticated user
            required: true
            schema:
              type: string
          - name: snippet_id
            in: path
            description: The ID of a project’s snippet
            required: true
            schema:
              type: integer
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: string
  - '/projects/{id}/snippets/{snippet_id}/files/{ref}/{file_path}/raw':
      get:
        summary: Snippet repository file content
        description: Returns the raw file content as plain text.
        operationId: snippetRepositoryFileContent
        parameters:
          - name: id
            in: path
            description: >-
              The ID or URL-encoded path of the project owned by the
              authenticated user
            required: true
            schema:
              type: string
          - name: snippet_id
            in: path
            description: The ID of a project’s snippet
            required: true
            schema:
              type: integer
          - name: ref
            in: path
            description: 'The name of a branch, tag or commit e.g. master'
            required: true
            schema:
              type: string
          - name: file_path
            in: path
            description: 'The URL-encoded path to the file, e.g. snippet%2Erb'
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: string
  - '/projects/{id}/snippets/{snippet_id}/user_agent_detail':
      get:
        summary: Get user agent details
        description: Available only for users with administrator access.
        operationId: getUserAgentDetails
        parameters:
          - name: id
            in: path
            description: >-
              The ID or URL-encoded path of the project owned by the
              authenticated user
            required: true
            schema:
              type: string
          - name: snippet_id
            in: path
            description: The ID of a snippet
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    user_agent:
                      type: string
                    ip_address:
                      type: string
                    akismet_submitted:
                      type: boolean
