openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / remote_mirrors'
  version: '1.0'
paths:
  '/projects/{id}/remote_mirrors':
    get:
      summary: List a project’s remote mirrors
      description: 'Returns an Array of remote mirrors and their statuses:'
      operationId: listAProjectRemoteMirrors
      parameters: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listAProjectRemoteMirrorsResponse'
    post:
      summary: Create a push mirror
      description: >-
        Push mirroring is disabled by default. You can enable it by including the optional parameter enabled when
        creating it:
      operationId: createAPushMirror
      parameters: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createAPushMirrorResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createAPushMirrorRequest'
  '/projects/{id}/remote_mirrors/{mirror_id}':
    get:
      summary: Get a single project’s remote mirror
      description: 'Returns a remote mirror and its statuses:'
      operationId: getASingleProjectRemoteMirror
      parameters: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getASingleProjectRemoteMirrorResponse'
    put:
      summary: Update a remote mirror’s attributes
      description: 'Toggle a remote mirror on or off, or change which types of branches are mirrored:'
      operationId: updateARemoteMirrorAttributes
      parameters:
        - name: mirror_id
          in: path
          description: The remote mirror ID.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updateARemoteMirrorAttributesResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateARemoteMirrorAttributesRequest'
    delete:
      summary: Delete a remote mirror
      description: Delete a remote mirror.
      operationId: deleteARemoteMirror
      parameters:
        - name: mirror_id
          in: path
          description: Remote mirror ID.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deleteARemoteMirrorResponse'
components:
  schemas:
    listAProjectRemoteMirrorsResponse:
      type: array
      items:
        type: object
        properties:
          enabled:
            type: boolean
          id:
            type: integer
          last_error:
            type: string
          last_successful_update_at:
            type: string
          last_update_at:
            type: string
          last_update_started_at:
            type: string
          only_protected_branches:
            type: boolean
          keep_divergent_refs:
            type: boolean
          update_status:
            type: string
          url:
            type: string
    getASingleProjectRemoteMirrorResponse:
      type: object
      properties:
        enabled:
          type: boolean
        id:
          type: integer
        last_error:
          type: string
        last_successful_update_at:
          type: string
        last_update_at:
          type: string
        last_update_started_at:
          type: string
        only_protected_branches:
          type: boolean
        keep_divergent_refs:
          type: boolean
        update_status:
          type: string
        url:
          type: string
    createAPushMirrorRequest:
      type: object
      properties:
        url:
          type: string
        enabled:
          type: boolean
        only_protected_branches:
          type: boolean
        keep_divergent_refs:
          type: boolean
      required:
        - url
    createAPushMirrorResponse:
      type: object
      properties:
        enabled:
          type: boolean
        id:
          type: integer
        last_error:
          type: string
        last_successful_update_at:
          type: string
        last_update_at:
          type: string
        last_update_started_at:
          type: string
        only_protected_branches:
          type: boolean
        keep_divergent_refs:
          type: boolean
        update_status:
          type: string
        url:
          type: string
    updateARemoteMirrorAttributesRequest:
      type: object
      properties:
        enabled:
          type: boolean
        only_protected_branches:
          type: boolean
        keep_divergent_refs:
          type: boolean
    updateARemoteMirrorAttributesResponse:
      type: object
      properties:
        enabled:
          type: boolean
        id:
          type: integer
        last_error:
          type: string
        last_successful_update_at:
          type: string
        last_update_at:
          type: string
        last_update_started_at:
          type: string
        only_protected_branches:
          type: boolean
        keep_divergent_refs:
          type: boolean
        update_status:
          type: string
        url:
          type: string
    deleteARemoteMirrorResponse:
      type: string
