paths:
  '/projects/{id}/remote_mirrors':
    get:
      summary: List a project’s remote mirrors
      description: 'Returns an Array of remote mirrors and their statuses:'
      operationId: listAProjectRemoteMirrors
      parameters: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    id:
                      type: integer
                    last_error:
                      type: string
                    last_successful_update_at:
                      type: string
                    last_update_at:
                      type: string
                    last_update_started_at:
                      type: string
                    only_protected_branches:
                      type: boolean
                    keep_divergent_refs:
                      type: boolean
                    update_status:
                      type: string
                    url:
                      type: string
    post:
      summary: Create a push mirror
      description: >-
        Push mirroring is disabled by default. You can enable it by including
        the optional parameter enabled when creating it:
      operationId: createAPushMirror
      parameters: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  enabled:
                    type: boolean
                  id:
                    type: integer
                  last_error:
                    type: string
                  last_successful_update_at:
                    type: string
                  last_update_at:
                    type: string
                  last_update_started_at:
                    type: string
                  only_protected_branches:
                    type: boolean
                  keep_divergent_refs:
                    type: boolean
                  update_status:
                    type: string
                  url:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                enabled:
                  type: boolean
                only_protected_branches:
                  type: boolean
                keep_divergent_refs:
                  type: boolean
              required:
                - url
  '/projects/{id}/remote_mirrors/{mirror_id}':
    get:
      summary: Get a single project’s remote mirror
      description: 'Returns a remote mirror and its statuses:'
      operationId: getASingleProjectRemoteMirror
      parameters: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  enabled:
                    type: boolean
                  id:
                    type: integer
                  last_error:
                    type: string
                  last_successful_update_at:
                    type: string
                  last_update_at:
                    type: string
                  last_update_started_at:
                    type: string
                  only_protected_branches:
                    type: boolean
                  keep_divergent_refs:
                    type: boolean
                  update_status:
                    type: string
                  url:
                    type: string
    put:
      summary: Update a remote mirror’s attributes
      description: >-
        Toggle a remote mirror on or off, or change which types of branches are
        mirrored:
      operationId: updateARemoteMirrorAttributes
      parameters:
        - name: mirror_id
          in: path
          description: The remote mirror ID.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  enabled:
                    type: boolean
                  id:
                    type: integer
                  last_error:
                    type: string
                  last_successful_update_at:
                    type: string
                  last_update_at:
                    type: string
                  last_update_started_at:
                    type: string
                  only_protected_branches:
                    type: boolean
                  keep_divergent_refs:
                    type: boolean
                  update_status:
                    type: string
                  url:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                enabled:
                  type: boolean
                only_protected_branches:
                  type: boolean
                keep_divergent_refs:
                  type: boolean
              required: []
    delete:
      summary: Delete a remote mirror
      description: Delete a remote mirror.
      operationId: deleteARemoteMirror
      parameters:
        - name: mirror_id
          in: path
          description: Remote mirror ID.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: string
