endpoints:
  - /sidekiq/queue_metrics:
      get:
        summary: Get the current Queue Metrics
        description: >-
          List information about all the registered queues, their backlog and
          their latency.
        operationId: getTheCurrentQueueMetrics
        parameters: []
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    queues:
                      type: object
                      properties:
                        default:
                          type: object
                          properties:
                            backlog:
                              type: integer
                            latency:
                              type: integer
  - /sidekiq/process_metrics:
      get:
        summary: Get the current Process Metrics
        description: >-
          List information about all the Sidekiq workers registered to process
          your queues.
        operationId: getTheCurrentProcessMetrics
        parameters: []
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    processes:
                      type: array
                      items:
                        type: object
                        properties:
                          hostname:
                            type: string
                          pid:
                            type: integer
                          tag:
                            type: string
                          started_at:
                            type: string
                          queues:
                            type: array
                            items:
                              type: string
                          labels:
                            type: array
                            items: {}
                          concurrency:
                            type: integer
                          busy:
                            type: integer
  - /sidekiq/job_stats:
      get:
        summary: Get the current Job Statistics
        description: List information about the jobs that Sidekiq has performed.
        operationId: getTheCurrentJobStatistics
        parameters: []
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    jobs:
                      type: object
                      properties:
                        processed:
                          type: integer
                        failed:
                          type: integer
                        enqueued:
                          type: integer
                        dead:
                          type: integer
  - /sidekiq/compound_metrics:
      get:
        summary: Get a compound response of all the previously mentioned metrics
        description: List all the currently available information about Sidekiq.
        operationId: getACompoundResponseOfAllThePreviouslyMentionedMetrics
        parameters: []
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    queues:
                      type: object
                      properties:
                        default:
                          type: object
                          properties:
                            backlog:
                              type: integer
                            latency:
                              type: integer
                    processes:
                      type: array
                      items:
                        type: object
                        properties:
                          hostname:
                            type: string
                          pid:
                            type: integer
                          tag:
                            type: string
                          started_at:
                            type: string
                          queues:
                            type: array
                            items:
                              type: string
                          labels:
                            type: array
                            items: {}
                          concurrency:
                            type: integer
                          busy:
                            type: integer
                    jobs:
                      type: object
                      properties:
                        processed:
                          type: integer
                        failed:
                          type: integer
                        enqueued:
                          type: integer
                        dead:
                          type: integer
