paths:
  /usage_data/metric_definitions:
    get:
      summary: Export metric definitions as a single YAML file
      description: >-
        Export all metric definitions as a single YAML file, similar to the
        Metrics Dictionary, for easier importing.
      operationId: exportMetricDefinitionsAsASingleYamlFile
      parameters: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: string
  /usage_data/queries:
    get:
      summary: Export Service Ping SQL queries
      description: >-
        This action is available only for the GitLab instance Administrator
        users.
      operationId: exportServicePingSqlQueries
      parameters: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: string
