paths:
  /version:
    get:
      summary: Version API
      description: >-
        Retrieve version information for this GitLab instance. Responds 200 OK
        for authenticated users.
      operationId: versionApi
      parameters: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                  revision:
                    type: string
