openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / instance_clusters'
  version: '1.0'
paths:
  /admin/clusters:
    get:
      summary: List instance clusters
      description: Returns a list of instance clusters.
      operationId: listInstanceClusters
      parameters: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listInstanceClustersResponse'
      tags:
        - instance_clusters
  '/admin/clusters/{cluster_id}':
    get:
      summary: Get a single instance cluster
      description: Returns a single instance cluster.
      operationId: getASingleInstanceCluster
      parameters:
        - name: cluster_id
          in: path
          description: The ID of the cluster
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getASingleInstanceClusterResponse'
      tags:
        - instance_clusters
    put:
      summary: Edit instance cluster
      description: Updates an existing instance cluster.
      operationId: editInstanceCluster
      parameters:
        - name: cluster_id
          in: path
          description: The ID of the cluster
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/editInstanceClusterResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/editInstanceClusterRequest'
      tags:
        - instance_clusters
    delete:
      summary: Delete instance cluster
      description: >-
        Deletes an existing instance cluster. Does not remove existing resources within the connected Kubernetes
        cluster.
      operationId: deleteInstanceCluster
      parameters:
        - name: cluster_id
          in: path
          description: The ID of the cluster
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
      tags:
        - instance_clusters
  /admin/clusters/add:
    post:
      summary: Add existing instance cluster
      description: Adds an existing Kubernetes instance cluster.
      operationId: addExistingInstanceCluster
      parameters: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getASingleInstanceClusterResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addExistingInstanceClusterRequest'
      tags:
        - instance_clusters
components:
  schemas:
    listInstanceClustersResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          name:
            type: string
          created_at:
            type: string
            format: date-time
          managed:
            type: boolean
          enabled:
            type: boolean
          domain:
            type: string
          provider_type:
            type: string
          platform_type:
            type: string
          environment_scope:
            type: string
          cluster_type:
            type: string
          user:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              username:
                type: string
              state:
                type: string
              avatar_url:
                type: string
              web_url:
                type: string
          platform_kubernetes:
            type: object
            properties:
              api_url:
                type: string
              namespace:
                type: string
              authorization_type:
                type: string
              ca_cert:
                type: string
          provider_gcp:
            type: string
          management_project:
            type: string
    getASingleInstanceClusterResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        created_at:
          type: string
          format: date-time
        managed:
          type: boolean
        enabled:
          type: boolean
        domain:
          type: string
        provider_type:
          type: string
        platform_type:
          type: string
        environment_scope:
          type: string
        cluster_type:
          type: string
        user:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            username:
              type: string
            state:
              type: string
            avatar_url:
              type: string
            web_url:
              type: string
        platform_kubernetes:
          type: object
          properties:
            api_url:
              type: string
            namespace:
              type: string
            authorization_type:
              type: string
            ca_cert:
              type: string
        provider_gcp:
          type: string
        management_project:
          type: string
    addExistingInstanceClusterRequest:
      type: object
      properties:
        name:
          type: string
        domain:
          type: string
        environment_scope:
          type: string
        management_project_id:
          type: integer
        enabled:
          type: boolean
        managed:
          type: boolean
        'platform_kubernetes_attributes[api_url]':
          type: string
        'platform_kubernetes_attributes[token]':
          type: string
        'platform_kubernetes_attributes[ca_cert]':
          type: string
        'platform_kubernetes_attributes[namespace]':
          type: string
        'platform_kubernetes_attributes[authorization_type]':
          type: string
      required:
        - name
        - 'platform_kubernetes_attributes[api_url]'
        - 'platform_kubernetes_attributes[token]'
    editInstanceClusterRequest:
      type: object
      properties:
        name:
          type: string
        domain:
          type: string
        environment_scope:
          type: string
        management_project_id:
          type: integer
        enabled:
          type: boolean
        managed:
          type: boolean
        'platform_kubernetes_attributes[api_url]':
          type: string
        'platform_kubernetes_attributes[token]':
          type: string
        'platform_kubernetes_attributes[ca_cert]':
          type: string
        'platform_kubernetes_attributes[namespace]':
          type: string
    editInstanceClusterResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        created_at:
          type: string
          format: date-time
        managed:
          type: boolean
        enabled:
          type: boolean
        domain:
          type: string
        provider_type:
          type: string
        platform_type:
          type: string
        environment_scope:
          type: string
        cluster_type:
          type: string
        user:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            username:
              type: string
            state:
              type: string
            avatar_url:
              type: string
            web_url:
              type: string
        platform_kubernetes:
          type: object
          properties:
            api_url:
              type: string
            namespace:
              type: string
            authorization_type:
              type: string
            ca_cert:
              type: string
        provider_gcp:
          type: string
        management_project:
          type: string
        project:
          type: string
