openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / protected_environments'
  version: '1.0'
paths:
  '/projects/{id}/protected_environments':
    get:
      summary: List protected environments
      description: 'Gets a list of protected environments from a project:'
      operationId: listProtectedEnvironments
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project owned by the authenticated user.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listProtectedEnvironmentsResponse'
      tags:
        - protected_environments
    post:
      summary: Protect repository environments
      description: 'Protects a single environment:'
      operationId: protectRepositoryEnvironments
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project owned by the authenticated user.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/protectRepositoryEnvironmentsRequest'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/protectRepositoryEnvironmentsRequest'
      tags:
        - protected_environments
  '/projects/{id}/protected_environments/{name}':
    get:
      summary: Get a single protected environment
      description: 'Gets a single protected environment:'
      operationId: getASingleProtectedEnvironment
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project owned by the authenticated user
          required: true
          schema:
            type: string
        - name: name
          in: path
          description: The name of the protected environment
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getASingleProtectedEnvironmentResponse'
      tags:
        - protected_environments
    delete:
      summary: Unprotect environment
      description: 'Unprotects the given protected environment:'
      operationId: unprotectEnvironment
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project owned by the authenticated user.
          required: true
          schema:
            type: string
        - name: name
          in: path
          description: The name of the protected environment.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
      tags:
        - protected_environments
components:
  schemas:
    listProtectedEnvironmentsResponse:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
          deploy_access_levels:
            type: array
            items:
              type: object
              properties:
                access_level:
                  type: integer
                access_level_description:
                  type: string
                user_id:
                  type: string
                group_id:
                  type: string
                group_inheritance_type:
                  type: integer
          required_approval_count:
            type: integer
    getASingleProtectedEnvironmentResponse:
      type: object
      properties:
        name:
          type: string
        deploy_access_levels:
          type: array
          items:
            type: object
            properties:
              access_level:
                type: integer
              access_level_description:
                type: string
              user_id:
                type: string
              group_id:
                type: string
              group_inheritance_type:
                type: integer
        required_approval_count:
          type: integer
    protectRepositoryEnvironmentsRequest:
      type: object
      properties:
        name:
          type: string
        deploy_access_levels:
          type: array
          items:
            type: string
        required_approval_count:
          type: integer
        approval_rules:
          type: array
          items:
            type: string
      required:
        - name
        - deploy_access_levels
