openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / packages/debian_group_distributions'
  version: '1.0'
paths:
  '/groups/{id}/debian_distributions':
    get:
      summary: List all Debian distributions in a group
      description: Lists Debian distributions in the given group.
      operationId: listAllDebianDistributionsInAGroup
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group.
          required: true
          schema:
            type: string
        - name: codename
          in: query
          description: Filter with specific codename.
          required: false
          schema:
            type: string
        - name: suite
          in: query
          description: Filter with specific suite.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listAllDebianDistributionsInAGroupResponse'
    post:
      summary: Create a Debian group distribution
      description: Creates a Debian group distribution.
      operationId: createADebianGroupDistribution
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createADebianGroupDistributionResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createADebianGroupDistributionRequest'
  '/groups/{id}/debian_distributions/{codename}':
    get:
      summary: Single Debian group distribution
      description: Gets a single Debian group distribution.
      operationId: singleDebianGroupDistribution
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user.
          required: true
          schema:
            type: string
        - name: codename
          in: path
          description: The codename of a distribution.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/singleDebianGroupDistributionResponse'
    put:
      summary: Update a Debian group distribution
      description: Updates a Debian group distribution.
      operationId: updateADebianGroupDistribution
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user.
          required: true
          schema:
            type: string
        - name: codename
          in: path
          description: The Debian distribution’s new codename.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updateADebianGroupDistributionResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateADebianGroupDistributionRequest'
    delete:
      summary: Delete a Debian group distribution
      description: Deletes a Debian group distribution.
      operationId: deleteADebianGroupDistribution
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user.
          required: true
          schema:
            type: string
        - name: codename
          in: path
          description: The codename of the Debian distribution.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deleteADebianGroupDistributionResponse'
  '/groups/{id}/debian_distributions/{codename}/key.asc':
    get:
      summary: Single Debian group distribution key
      description: Gets a single Debian group distribution key.
      operationId: singleDebianGroupDistributionKey
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the group owned by the authenticated user.
          required: true
          schema:
            type: string
        - name: codename
          in: path
          description: The codename of a distribution.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/singleDebianGroupDistributionKeyResponse'
components:
  schemas:
    listAllDebianDistributionsInAGroupResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          codename:
            type: string
          suite:
            type: string
          origin:
            type: string
          label:
            type: string
          version:
            type: string
          description:
            type: string
          valid_time_duration_seconds:
            type: string
          components:
            type: array
            items:
              type: string
          architectures:
            type: array
            items:
              type: string
    singleDebianGroupDistributionResponse:
      type: object
      properties:
        id:
          type: integer
        codename:
          type: string
        suite:
          type: string
        origin:
          type: string
        label:
          type: string
        version:
          type: string
        description:
          type: string
        valid_time_duration_seconds:
          type: string
        components:
          type: array
          items:
            type: string
        architectures:
          type: array
          items:
            type: string
    singleDebianGroupDistributionKeyResponse:
      type: string
    createADebianGroupDistributionRequest:
      type: object
      properties:
        codename:
          type: string
        suite:
          type: string
        origin:
          type: string
        label:
          type: string
        version:
          type: string
        description:
          type: string
        valid_time_duration_seconds:
          type: integer
      required:
        - codename
    createADebianGroupDistributionResponse:
      type: object
      properties:
        id:
          type: integer
        codename:
          type: string
        suite:
          type: string
        origin:
          type: string
        label:
          type: string
        version:
          type: string
        description:
          type: string
        valid_time_duration_seconds:
          type: string
        components:
          type: array
          items:
            type: string
        architectures:
          type: array
          items:
            type: string
    updateADebianGroupDistributionRequest:
      type: object
      properties:
        suite:
          type: string
        origin:
          type: string
        label:
          type: string
        version:
          type: string
        description:
          type: string
        valid_time_duration_seconds:
          type: integer
    updateADebianGroupDistributionResponse:
      type: object
      properties:
        id:
          type: integer
        codename:
          type: string
        suite:
          type: string
        origin:
          type: string
        label:
          type: string
        version:
          type: string
        description:
          type: string
        valid_time_duration_seconds:
          type: integer
        components:
          type: array
          items:
            type: string
        architectures:
          type: array
          items:
            type: string
    deleteADebianGroupDistributionResponse:
      type: string
