openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / dependencies'
  version: '1.0'
paths:
  '/projects/{id}/dependencies':
    get:
      summary: List project dependencies
      description: >-
        Get a list of project dependencies. This API partially mirroring Dependency List feature. This list can be
        generated only for languages and package managers supported by Gemnasium.
      operationId: listProjectDependencies
      parameters:
        - name: id
          in: path
          description: The ID or URL-encoded path of the project.
          required: true
          schema:
            type: string
        - name: package_manager
          in: query
          description: >-
            Returns dependencies belonging to specified package manager. Valid values: bundler, composer, conan, go,
            gradle, maven, npm, nuget, pip, pipenv, yarn, sbt, or setuptools.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listProjectDependenciesResponse'
      tags:
        - dependencies
components:
  schemas:
    listProjectDependenciesResponse:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
          version:
            type: string
          package_manager:
            type: string
          dependency_file_path:
            type: string
          vulnerabilities:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                severity:
                  type: string
