openapi: 3.0.2
info:
  title: 'GitLabKit: REST API / metadata'
  version: '1.0'
paths:
  /metadata:
    get:
      summary: Metadata API
      description: Retrieve metadata information for this GitLab instance.
      operationId: metadataApi
      parameters:
        - name: version
          in: query
          required: false
          schema:
            type: string
        - name: revision
          in: query
          required: false
          schema:
            type: string
        - name: kas
          in: query
          required: false
          schema:
            type: string
        - name: kas.enabled
          in: query
          required: false
          schema:
            type: string
        - name: kas.externalUrl
          in: query
          required: false
          schema:
            type: string
        - name: kas.version
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/metadataApiResponse'
      tags:
        - metadata
components:
  schemas:
    metadataApiResponse:
      type: object
      properties:
        version:
          type: string
        revision:
          type: string
        kas:
          type: object
          properties:
            enabled:
              type: boolean
            externalUrl:
              type: string
            version:
              type: string
